### ISSUE TITLE
Unable to two-factor authenticate - public key and password (using keyboard-interactive) both fail.

### ISSUE THREAD

**Issue by jamoros** [mwiede/jsch#107]
Greetings! I just upgraded from 0.1.55 to this fork of 0.1.72. I was hoping the upgrade will help fix the issue I am currently having. I know it is not an issue with the private key or password because I am able to connect and authenticate using another library (maverick synergy), however since we have services already written with JSCH I was hoping to be able to just drop in this jar file and go from there.

The issue is that this new client we're logging into forces two factor authentication. Public key and then password. Here is the main piece of code to log in:

```
Session session = null;
 ChannelSftp channel = null;

        try {
            JSch jsch = new JSch();
            JSch.setLogger(new JSCHLogger());

            jsch.addIdentity(PRIVATE_KEY_PATH, PASS_PHRASE);

            session = jsch.getSession(QA_USERNAME, HOST, PORT);
            session.setPassword(QA_PASSWORD);

            UserInfo ui = new MyUserInfo();
            session.setUserInfo(ui);

            Properties config = new Properties();

            config.put("StrictHostKeyChecking", "no");

            config.put("cipher.c2s", "aes256-cbc,aes128-cbc");
            config.put("cipher.s2c", "aes256-cbc,aes128-cbc");
            config.put("PubkeyAcceptedKeyTypes", "ssh-rsa," + JSch.getConfig("PubkeyAcceptedKeyTypes"));

            session.setConfig(config);

            session.connect(Integer.MAX_VALUE);

            channel = (ChannelSftp) session.openChannel("sftp");
            channel.connect(Integer.MAX_VALUE);
} catch(Exception ex) {
 LOG.error(ex);
}
````
For the sake of brevity I removed the rest of the code, as this is currently failing when we try to connect via the session. The MyUserInfo class is the standard implementation of UIKeyboardInteractive and UserInfo found in many examples that simply returns the password.

Below is the log when I run the code above
```
INFO: Connecting to sftp.x.com port 22
INFO: Connection established
INFO: Remote version string: SSH-2.0-1.82_sshlib GlobalSCAPE
INFO: Local version string: SSH-2.0-JSCH-0.1.72
INFO: CheckCiphers: chacha20-poly1305@openssh.com
INFO: CheckKexes: curve25519-sha256,curve25519-sha256@libssh.org,curve448-sha512
INFO: CheckSignatures: ssh-ed25519,ssh-ed448
DEBUG: server_host_key proposal before known_host reordering is: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa
DEBUG: server_host_key proposal after known_host reordering is: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa
INFO: SSH_MSG_KEXINIT sent
INFO: SSH_MSG_KEXINIT received
INFO: kex: server: diffie-hellman-group16-sha512,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1
INFO: kex: server: ssh-rsa
INFO: kex: server: aes256-cbc,3des-cbc,aes128-cbc
INFO: kex: server: aes256-cbc,3des-cbc,aes128-cbc
INFO: kex: server: hmac-sha2-512,hmac-sha2-256,hmac-sha1,hmac-md5,hmac-sha1-96,hmac-md5-96
INFO: kex: server: hmac-sha2-512,hmac-sha2-256,hmac-sha1,hmac-md5,hmac-sha1-96,hmac-md5-96
INFO: kex: server: zlib,none
INFO: kex: server: zlib,none
INFO: kex: server: 
INFO: kex: server: 
INFO: kex: client: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,ext-info-c
INFO: kex: client: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa
INFO: kex: client: aes256-cbc,aes128-cbc
INFO: kex: client: aes256-cbc,aes128-cbc
INFO: kex: client: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
INFO: kex: client: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
INFO: kex: client: none
INFO: kex: client: none
INFO: kex: client: 
INFO: kex: client: 
INFO: kex: algorithm: diffie-hellman-group16-sha512
INFO: kex: host key algorithm: ssh-rsa
INFO: kex: server->client cipher: aes256-cbc MAC: hmac-sha2-256 compression: none
INFO: kex: client->server cipher: aes256-cbc MAC: hmac-sha2-256 compression: none
INFO: SSH_MSG_KEXDH_INIT sent
INFO: expecting SSH_MSG_KEXDH_REPLY
INFO: ssh_rsa_verify: ssh-rsa signature true
WARN: Permanently added 'sftp.x.com' (RSA) to the list of known hosts.
INFO: SSH_MSG_NEWKEYS sent
INFO: SSH_MSG_NEWKEYS received
INFO: SSH_MSG_SERVICE_REQUEST sent
INFO: SSH_MSG_SERVICE_ACCEPT received
Server message: 
INFO: Authentications that can continue: publickey,keyboard-interactive,password
INFO: Next authentication method: publickey
DEBUG: PubkeyAcceptedAlgorithms = ssh-rsa,ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa
DEBUG: No server-sig-algs found, using PubkeyAcceptedAlgorithms = [ssh-rsa, ssh-ed25519, ecdsa-sha2-nistp256, ecdsa-sha2-nistp384, ecdsa-sha2-nistp521, rsa-sha2-512, rsa-sha2-256, ssh-rsa]
DEBUG: ssh-rsa preauth failure
DEBUG: rsa-sha2-512 preauth failure
DEBUG: rsa-sha2-256 preauth failure
DEBUG: ssh-rsa preauth failure
INFO: Authentications that can continue: keyboard-interactive,password
INFO: Next authentication method: keyboard-interactive
INFO: Authentications that can continue: password
INFO: Next authentication method: password
promptPassword: Password for User@sftp.x.com
Returning password.
promptPassword: Password for User@sftp.x.com
Returning password.
promptPassword: Password for User@sftp.x.com
Returning password.
promptPassword: Password for User@sftp.x.com
Returning password.
INFO: Login trials exceeds 6
INFO: Disconnecting from cgsftp.canaccord.com port 22
2021-12-21 18:10:20,414 ERROR [com.utils.JSchUtilsdLargeTest] - <Failed>
com.jcraft.jsch.JSchException: Auth fail
	at com.jcraft.jsch.Session.connect(Session.java:524)
```

Is there anything that someone sees that I am missing why my authentication fails? As mentioned Im able to connect and authenticate via another library and WinScp. However, I've been having this same issue with JSCH since 1.55 and now 1.72.

Everything is pretty much standard, the RSA key is 4096 bits, not sure if that would be an issue.

Any help would be greatly appreciated!

Thank you!

**Comment by norrisjeremy** [comment]
Would you be able to capture output from a full successful login from CLI using the `ssh -vvv` command?
I’m not 100% certain if JSch is currently capable of performing this type of 2FA.
The `ssh -vvv` output from a full successful login should provide some details on working authentication packet flow from the server, which we can compare with the JSch implementation to see if it would work (or if not what changes may be required to have it work).

**Comment by jamoros** [comment]
Hey Jeremy, unfortunately I won't be able to do that. I was able to get it to work with another library. We're still using JSch for other things but for this specific issue we had to move on, time was of the essence. Thank you for your time!

**Comment by jamoros** [comment]
I ran the command for you, unfortunately Im unable to connect because it complains about the password, however this is the majority of the log before key authentication:

OpenSSH_7.2p2 Ubuntu-4ubuntu2.10, OpenSSL 1.0.2g  1 Mar 2016
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug2: resolving "sftp.x.com" port 22
debug2: ssh_connect_direct: needpriv 0
debug1: Connecting to sftp.x.com [206.25.70.159] port 22.
debug1: Connection established.
key_load_public: invalid format
debug1: identity file PrivKey type -1
debug1: key_load_public: No such file or directory
debug1: identity file PrivKey-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.10
debug1: Remote protocol version 2.0, remote software version 1.82_sshlib GlobalSCAPE
debug1: no match: 1.82_sshlib GlobalSCAPE
debug2: fd 3 setting O_NONBLOCK
debug1: Authenticating to sftp.x.com:22 as 'PrivKey'
debug3: hostkeys_foreach: reading file "/home/.ssh/known_hosts"
debug3: record_hostkey: found key type RSA in file /home/.ssh/known_hosts:148
debug3: load_hostkeys: loaded 1 keys from sftp.x.com
debug3: order_hostkeyalgs: prefer hostkeyalgs: ssh-rsa-cert-v01@openssh.com,rsa-sha2-512,rsa-sha2-256,ssh-rsa
debug3: send packet: type 20
debug1: SSH2_MSG_KEXINIT sent
debug3: receive packet: type 20
debug1: SSH2_MSG_KEXINIT received
debug2: local client KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,ext-info-c
debug2: host key algorithms: ssh-rsa-cert-v01@openssh.com,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc,3des-cbc
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc,3des-cbc
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com,zlib
debug2: compression stoc: none,zlib@openssh.com,zlib
debug2: languages ctos: 
debug2: languages stoc: 
debug2: first_kex_follows 0 
debug2: reserved 0 
debug2: peer server KEXINIT proposal
debug2: KEX algorithms: diffie-hellman-group16-sha512,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1
debug2: host key algorithms: ssh-rsa
debug2: ciphers ctos: aes256-cbc,3des-cbc,aes128-cbc
debug2: ciphers stoc: aes256-cbc,3des-cbc,aes128-cbc
debug2: MACs ctos: hmac-sha2-512,hmac-sha2-256,hmac-sha1,hmac-md5,hmac-sha1-96,hmac-md5-96
debug2: MACs stoc: hmac-sha2-512,hmac-sha2-256,hmac-sha1,hmac-md5,hmac-sha1-96,hmac-md5-96
debug2: compression ctos: zlib,none
debug2: compression stoc: zlib,none
debug2: languages ctos: 
debug2: languages stoc: 
debug2: first_kex_follows 0 
debug2: reserved 0 
debug1: kex: algorithm: diffie-hellman-group-exchange-sha1
debug1: kex: host key algorithm: ssh-rsa
debug1: kex: server->client cipher: aes128-cbc MAC: hmac-sha2-256 compression: none
debug1: kex: client->server cipher: aes128-cbc MAC: hmac-sha2-256 compression: none
debug3: send packet: type 34
debug1: SSH2_MSG_KEX_DH_GEX_REQUEST(2048<8192<8192) sent
debug3: receive packet: type 31
debug1: got SSH2_MSG_KEX_DH_GEX_GROUP
debug2: bits set: 1001/2048
debug3: send packet: type 32
debug1: SSH2_MSG_KEX_DH_GEX_INIT sent
debug3: receive packet: type 33
debug1: got SSH2_MSG_KEX_DH_GEX_REPLY
debug1: Server host key: ssh-rsa SHA256:fXehkOG1StRPpOlCnTMFquuv4LkUdUs0ZzTKt/d7U3M

Hope this helps!
