### ISSUE TITLE
Getting garbage in InputStream when connecting to socket via proxy

### ISSUE THREAD

**Issue by ellabrom** [mwiede/jsch#110]
Sometimes, when connecting to socket via proxy (in Session.java), we get from InputStream some garbage , the process is stuck for about a minute and then below error is thrown:
"connection is closed by foreign host"
What can be a reason for such behavior?
Attaching log with error and "garbage string" (look for word ella
[error_log.txt](https://github.com/mwiede/jsch/files/7876991/error_log.txt)
)

**Comment by norrisjeremy** [comment]
1. Can you provide example code displaying how your application is using the JSch library (it’s not obvious to me based upon your description what exactly you are doing)?
2. What version of JSch are you utilizing?
3. Are you using the binary Jar file published to Maven Central, or are you self-compiling the JSch library from source?

**Comment by ellabrom** [comment]
Hi,

1. Code example:
         private JSch jsch;
	private Session session;
...
        jsch = new JSch();
....
       session = jsch.getSession(hostProperties.getUser(), hostProperties.getHostName(), hostProperties.getPort());
.....
       ProxyHTTP  proxy = new ProxyHTTP(proxyAddress,proxyPort);
       session.setProxy(proxy);
	session.setTimeout(SESSION_TIMEOUT);
	session.connect();
2. 0.1.72
3. We self-compile only below classes: Session, KnownHosts, ChannelSftp. All the rest  - using binary jar.

Thanks,
Ella

**Comment by norrisjeremy** [comment]
Why do you self-compile the Session, KnownHosts & ChannelSftp classes? Are you applying custom changes to these classes?
