### ISSUE TITLE
oss-parent deprecated?

### ISSUE THREAD

**Issue by norrisjeremy** [mwiede/jsch#116]
I noticed that the `org.sonatype.oss:oss-parent` is deprecated according to their Github: https://github.com/sonatype/oss-parents.

Should we remove this from the pom.xml? I'm not sure if this would have any impact on the release process you utilize and would require other changes besides simply removing it from the pom.xml?

**Comment by norrisjeremy** [comment]
I've include this in #113. Let me know if additional changes are needed so as to not impact your release process or ability to publish to Sonatype / Maven Central.

**Comment by norrisjeremy** [comment]
I think I've updated #113 to repair your release workflow, according to [Sonatype's docs](https://central.sonatype.org/publish/publish-maven/).
I think the one change you will have to make is to change your `MVN_REPO_ID` value to `ossrh`.

**Comment by mwiede** [comment]
Thanks @norrisjeremy release 0.2.0 is published
