### ISSUE TITLE
Still throws JSchException: invalid privatekey

### ISSUE THREAD

**Issue by wangchenOS** [mwiede/jsch#12]
I run my program using this version to connect remote host by private id_rsa file on mac ,but program run error throws this exception:

com.jcraft.jsch.JSchException: invalid privatekey: [B@9807454
	at com.jcraft.jsch.KeyPair.load(KeyPair.java:666)
	at com.jcraft.jsch.KeyPair.load(KeyPair.java:563)
	at com.jcraft.jsch.IdentityFile.newInstance(IdentityFile.java:40)
	at com.jcraft.jsch.JSch.addIdentity(JSch.java:425)
	at com.jcraft.jsch.JSch.addIdentity(JSch.java:406)

![image](https://user-images.githubusercontent.com/8773246/88247632-0443ba00-ccd1-11ea-86b5-54ebe816cd03.png)

ssh version:
OpenSSH_7.9p1, LibreSSL 2.7.3
The id_rsa file  is generated by the command " ssh-keygen -t rsa" ,  so current version does not support this encryption algorithm ?

**Comment by mwiede** [comment]
you have the same issue as described in https://stackoverflow.com/questions/53134212/invalid-privatekey-when-using-jsch

your ssh version is >= 7.8, so the generated key has OPENSSH format, which has `-----BEGIN OPENSSH PRIVATE KEY-----` in the first line of the private key. This type of key is not supported by Jsch as of now.

Please generate the key using ` ssh-keygen -t rsa -m PEM`, which triggers ssh-keygen to use legacy key format. Check that you have `-----BEGIN RSA PRIVATE KEY-----` in the first line of the private key.

**Comment by wangchenOS** [comment]
Got it

**Comment by raghulkrishna** [comment]
is this supported now ? i am getting the error 

com.jcraft.jsch.JSchException: invalid privatekey: [B@49e202ad

**Comment by hmmmk** [comment]
> is this supported now ? i am getting the error
> 
> com.jcraft.jsch.JSchException: invalid privatekey: [B@49e202ad

Same question here. I have the same error with openssh
