### ISSUE TITLE
Issue "Algorithm negotiation fail" probably in guess function

### ISSUE THREAD

**Issue by Infineon12** [mwiede/jsch#136]
Hello,

using Version 0.2.0 with Coretto Java 8 and BouncyCastle Provider.

> 2022-04-05 14:25:24,944  INFO Connecting to *** port 22
> 2022-04-05 14:25:24,952  INFO Connection established
> 2022-04-05 14:25:24,974  INFO Remote version string: SSH-2.0-OpenSSH_7.4
> 2022-04-05 14:25:24,974  INFO Local version string: SSH-2.0-JSCH_0.2.0
> 2022-04-05 14:25:24,974  INFO CheckCiphers: aes128-cbc
> 2022-04-05 14:25:24,974  INFO CheckKexes: curve25519-sha256,curve25519-sha256@libssh.org,curve448-sha512
> 2022-04-05 14:25:24,976  INFO CheckSignatures: ssh-ed25519,ssh-ed448
> 2022-04-05 14:25:24,976  DEBUG server_host_key proposal before known_host reordering is: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256
> 2022-04-05 14:25:24,976  DEBUG server_host_key proposal after known_host reordering is: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256
> 2022-04-05 14:25:24,976  INFO SSH_MSG_KEXINIT sent
> 2022-04-05 14:25:24,981  INFO SSH_MSG_KEXINIT received
> 2022-04-05 14:28:43,157  INFO kex: server: curve25519-sha256@libssh.org
> 2022-04-05 14:28:43,157  INFO kex: server: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519
> 2022-04-05 14:28:43,157  INFO kex: server: chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
> 2022-04-05 14:28:43,157  INFO kex: server: chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
> 2022-04-05 14:28:43,157  INFO kex: server: hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com
> 2022-04-05 14:28:43,157  INFO kex: server: hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com
> 2022-04-05 14:28:43,157  INFO kex: server: none,zlib@openssh.com
> 2022-04-05 14:28:43,157  INFO kex: server: none,zlib@openssh.com
> 2022-04-05 14:28:43,157  INFO kex: server:
> 2022-04-05 14:28:43,157  INFO kex: server:
> 2022-04-05 14:28:43,158  INFO kex: client: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,ext-info-c
> 2022-04-05 14:28:43,158  INFO kex: client: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256
> 2022-04-05 14:28:43,158  INFO kex: client: aes128-cbc,3des-cbc,blowfish-cbc
> 2022-04-05 14:28:43,158  INFO kex: client: aes128-cbc,3des-cbc,blowfish-cbc
> 2022-04-05 14:28:43,158  INFO kex: client: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
> 2022-04-05 14:28:43,158  INFO kex: client: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
> 2022-04-05 14:28:43,158  INFO kex: client: none
> 2022-04-05 14:28:43,158  INFO kex: client: none
> 2022-04-05 14:28:43,158  INFO kex: client:
> 2022-04-05 14:28:43,158  INFO kex: client:
> 2022-04-05 14:28:43,158  INFO Disconnecting from *** port 22
> 2022-04-05 14:36:00,207 ERROR Error initializing JSch Sessioncom.jcraft.jsch.JSchException: Algorithm negotiation fail

We debugged deep into the class com.jcraft.jsch.KeyExchange where we took a look into the "String[] guess(Session session, byte[]I_S, byte[]I_C)" function.

Based on the proposals from the log above he does find 2 matches and puts them into the guess[]:

["curve25519-sha256@libssh.org", "ssh-ed25519", null, null, null, null, null, null, null, null]

But due to the fact that he does not find a third match in following loop he does call the return null at guess[2]==null

```
for(int i=0; i<PROPOSAL_MAX; i++){
      byte[] sp=sb.getString();  // server proposal
      byte[] cp=cb.getString();  // client proposal
      int j=0;
      int k=0;
      loop:
      while(j<cp.length){
        while(j<cp.length && cp[j]!=',')j++; 
        if(k==j) return null;
        String algorithm=Util.byte2str(cp, k, j-k);
        int l=0;
        int m=0;
        while(l<sp.length){
          while(l<sp.length && sp[l]!=',')l++; 
          if(m==l) return null;
          if(algorithm.equals(Util.byte2str(sp, m, l-m))){
            guess[i]=algorithm;
            break loop;
          }
          l++;
          m=l;
        }
        j++;
        k=j;
      }
      if(j==0){
        guess[i]="";
      }
      else if(guess[i]==null){
        return null;
      }
    }
```

We currently are completely lost what the issue is here.
Any suggestions how we can continue to solve the issue?

Thanks in advance

**Comment by norrisjeremy** [comment]
Hi @Infineon12,

The SSH server is only configured to accept the following Cipher algorithms:
```
server: chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
```

But you have configured JSch to only use the following Cipher algorithms:
```
client: aes128-cbc,3des-cbc,blowfish-cbc
```

Since JSch and the SSH server do not have any mutually agreeable Cipher algorithms, the connection fails.

You will need to either:
1. Reconfigure the SSH server to support one or more of `aes128-cbc,3des-cbc,blowfish-cbc`.
2. Or reconfigure JSch to support one or more of `chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr`.

Thanks,
Jeremy

**Comment by norrisjeremy** [comment]
Hi @Infineon12,

Did you have a chance to review my earlier comment?

Thanks,
Jeremy

**Comment by Infineon12** [comment]
Sorry for not replying.

Sure your comment helped and fixed the issue.

Thanks
