### ISSUE TITLE
IOException when using to connect using JSch jar 0.1.55

### ISSUE THREAD

**Issue by nsanjay12** [mwiede/jsch#149]
Caused by: com.jcraft.jsch.JSchException: Session.connect: java.io.IOException: End of IO Stream Read
	at com.jcraft.jsch.Session.connect(Session.java:565)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at com.eibus.applicationconnector.ftp.CordysSFTPClient.connectOnce(CordysSFTPClient.java:124)
	at com.eibus.applicationconnector.ftp.CordysSFTPClient.connect(CordysSFTPClient.java:64)

**Comment by norrisjeremy** [comment]
Hi @nsanjay12,

Are you able to replicate this issue with the most recent JSch release: 0.2.1?

Thanks,
Jeremy

**Comment by nsanjay12** [comment]
@norrisjeremy I need to check with 0.2.1 and will update

**Comment by nsanjay12** [comment]
Hi @norrisjeremy We tried with JSCH 0.2.1 but got Unsupported version error. While with JSCH 0.1.55 we see connection is closed by foreign host. Any clue on the connection is closed issue?

**Comment by norrisjeremy** [comment]
HI @nsanjay12,

It's tough to tell with such an old version (note that 0.1.55 is a release prior to this particular fork).
When you say that you are getting an `Unsupported version error`, do you mean that you are using an older Java release (i.e., older than Java 8)?

Thanks,
Jeremy

**Comment by nsanjay12** [comment]
Yes its running on Java 1.7

**Comment by norrisjeremy** [comment]
Hi @nsanjay12,

Unfortunately, this JSch fork only supports Java 8+. And since 0.1.55 is release from prior to this particular fork, I'm not sure how much help we can provide. If you can update to Java 8+, you should be able to test with our 0.2.1 release.

Thanks,
Jeremy

**Comment by nsanjay12** [comment]
Actually this jar is being utlilized inside a product which cannot be run on latest java version making us helpless to use higher java versions. Thank you so much for the inputs @norrisjeremy
