### ISSUE TITLE
Algorithm Negotiation fails on update from 0.1.55 to 0.2.1

### ISSUE THREAD

**Issue by precoder** [mwiede/jsch#155]
Hello,

We have updated our Jsch Library from 0.1.55 to 0.2.1 and since then we get 

`com.jcraft.jsch.JSchException: Algorithm negotiation fail   at com.jcraft.jsch.Session.receive_kexinit(Session.java:604)`
With multiple SFTP Servers that are not under our control and not using the new ciphers.

I have set the "server_host_key" cipher list by using same list as on the 0.1.55:
`session.setConfig("server_host_key", "ssh-rsa,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521");`

Then it started to work again.
As I can see from the code, latest version supports: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256

My question is, the behavior about the "setConfig" method of Session, is that additive on existing list of ciphers or does it replace the existing list?
So do I need to add the new ciphers on the list when I call "setConfig"?

**Comment by norrisjeremy** [comment]
Hi @precoder,

`setConfig()` is not additive: it fully replaces the list of ciphers.

Thanks,
Jeremy
