### ISSUE TITLE
sftp.ls Vector change to support ArrayList instead.  Vector marked as obsolete.

### ISSUE THREAD

**Issue by wigglethorpe** [mwiede/jsch#158]
I'm just curious if there's any plans to replace the vector implementation of ls to an array list instead?  I know this would be a breaking change in terms of existing code, but if this is considered the replacement fork for the original, shouldn't it be at least updated to remove obsolete classes going forward?  I do appreciate the work for moving this thing forward.  I was afraid it was dead, since the original maintainer company isn't responding to anything just like mwede article said.  I do appreciate it.

**Comment by mwiede** [comment]
vector is already implementing `java.util.List`. What do you mean by "vector deprecated"?

**Comment by wigglethorpe** [comment]
If you look at the documentation for 1.8, and I'm sure it's true of 9 and beyond, Vector is marked as obsolete.  I'm sorry, not deprecated, but obsolete.  They recommend ArrayList<> as a replacement. Incorrect wording, I apologize.  And I'm reading obsolete is not the same as deprecated, so I do seem to think I'm talking out of ignorance of what the various terms in the documentation mean.

**Comment by wigglethorpe** [comment]
If you look at the documentation for 1.8, and I'm sure it's true of 9 and beyond, Vector is marked as obsolete.  I'm sorry, not deprecated, but obsolete.  They recommend ArrayList<> as a replacement. Incorrect wording on my part and I changed the subject to reflect it, I apologize.  And I was reading obsolete is equivalent as deprecated (i.e. it would eventually be dropped), so I do seem to think I'm talking out of ignorance of what the those two terms mean in the base Java documentation.
