### ISSUE TITLE
What is the host key algorithm used in jsch 0.1.54? 

### ISSUE THREAD

**Issue by nsanjay12** [mwiede/jsch#159]

**Comment by nsanjay12** [comment]
This jar when used with **ssh-rsa** is giving issues. While works fine with **rsa-sha2-512**

**Comment by mwiede** [comment]
what do you mean by "this" jar? As mentioned in the release notes of [2.0](https://github.com/mwiede/jsch/releases/tag/jsch-0.2.0), ssh-rsa is disabled by default

**Comment by nsanjay12** [comment]
This jar refers to jsch 0.1.54

**Comment by nsanjay12** [comment]
@mwiede  Also can you please let us know where we can find the release notes for jsch jars as we did not find it anywhere.

**Comment by mwiede** [comment]
the release notes of original jsch where written to https://github.com/mwiede/jsch/blob/master/ChangeLog
The host key types were `ssh-dss,ssh-rsa, ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521` as stated in the original reademe https://github.com/mwiede/jsch/blob/master/README

**Comment by nsanjay12** [comment]
@mwiede I do not see the jar version mentioned as 0.1.54 in the readme link provided above. Can you please help us to confirm that its the README for 0.1.54?

**Comment by mwiede** [comment]
Have a look at the change log not readme
