### ISSUE TITLE
when the latest version will be published?

### ISSUE THREAD

**Issue by mysjz-qingquanshishangliu** [mwiede/jsch#16]
Hi,
I noticed that the current version is 0.1.59, and below maven reposotory can be used.
<dependency>
  <groupId>com.github.mwiede</groupId>
  <artifactId>jsch</artifactId>
  <version>0.1.59</version>
</dependency>

When the latest com.github.mwiede.jsch dependency will be published? because the "support for openssh-v1-private-key format" can fix my issue :)

**Comment by mwiede** [comment]
Yes I will release it until end of this week

**Comment by mwiede** [comment]
closing as release 0.1.60 is published
