### ISSUE TITLE
Check for length of Private Key type is wrong

### ISSUE THREAD

**Issue by Maronius** [mwiede/jsch#188]
https://github.com/mwiede/jsch/blob/ccbf767ad7688546b3d29ff52f23c1449b3fcb56/src/main/java/com/jcraft/jsch/KeyPair.java#L602
Hy,
The check has to be extended:
(prvkey[3]==7 || prvkey[3]==9 || prvkey[3]==11 || prvkey[3]==19)
Otherwise the following comparisons in Line 621 and 624 are useles.

**Comment by norrisjeremy** [comment]
Hi @Maronius,

Good catch. See #189.

Thanks,
Jeremy

**Comment by mwiede** [comment]
closing as fix is released with 0.2.3
