### ISSUE TITLE
Include TestBCrypt.java unit test?

### ISSUE THREAD

**Issue by norrisjeremy** [mwiede/jsch#20]
Do you think a copy of the TestBCrypt.java unit tests should also be incorporated into the build?

**Comment by norrisjeremy** [comment]
Can you share the location of the version of `BCrypt.java` that you utilized? Then I can pull the `TestBCrypt.java` from the same location and adapt it?

**Comment by mwiede** [comment]
I took it from https://github.com/kruton/jbcrypt/blob/master/jbcrypt/src/main/java/org/mindrot/jbcrypt/BCrypt.java

The test is located at https://github.com/kruton/jbcrypt/blob/master/jbcrypt/src/test/java/org/mindrot/jbcrypt/TestBCrypt.java

**Comment by norrisjeremy** [comment]
Great, thanks! See #30.
