### ISSUE TITLE
Missing Jumphost.java in the examples directory

### ISSUE THREAD

**Issue by Tilden18** [mwiede/jsch#201]
In the Readme states the below
- JumpHosts.java
  This program will demonstrate SSH through jump hosts.

but the JumpHosts.java file is missing in the examples directory. c

**Comment by norrisjeremy** [comment]
Hi @Tilden18,

FYI, I pulled the copy of this from the original author's site I noted above and have included it in PR #200.

Btw, this code seems to just used port-forwarding, so I don't believe operates in the same manner as OpenSSH's `ProxyJump` functionality (which I believe accomplishes jump host type functionality without using port-forwarding), if that is what you are looking for.

Thanks,
Jeremy

**Comment by Tilden18** [comment]
Hi Jeremy, 
yes, I was looking for ProxyJump functionality (with Password and Key authorization). do you support this in jsch?  

Similar to this. 
https://github.com/hierynomus/sshj/blob/master/examples/src/main/java/net/schmizz/sshj/examples/Jump.java

**Comment by norrisjeremy** [comment]
Hi @Tilden18,

JSch doesn't currently support the `ProxyJump` specific directive as implemented in OpenSSH.
However, it should be possibly to perform something akin to it using port forwarding (as the [JumpHosts.java)](https://github.com/mwiede/jsch/blob/master/examples/JumpHosts.java) example implements.
Also, from my limited understanding of SSHJ, the example you linked from it appears to be similar to the [JumpHosts.java](https://github.com/mwiede/jsch/blob/master/examples/JumpHosts.java) example, in that it utilizes port forwarding.

Thanks,
Jeremy
