### ISSUE TITLE
How to use this with JDK8 ?

### ISSUE THREAD

**Issue by feiyan-gh** [mwiede/jsch#202]
Hello, sorry maybe this is a noob question, I am trying to upgrade the jsch-0.1.55.jar came with Apache Ant because the scp module does not work.

My server only have JDK 8, not JDK 17 so I cannot run mvnw package.

Where can I find a compiled jar of this library? I checked the release page it seems only contain source file.

**Comment by mwiede** [comment]
It's on maven central see https://search.maven.org/artifact/com.github.mwiede/jsch/0.2.3/jar

**Comment by mwiede** [comment]
Be aware that not all features are available with java 8 as mentioned on the readme.
