### ISSUE TITLE
Stop SSH_MSG_SERVICE_REQUEST from being sent

### ISSUE THREAD

**Issue by ThnksCJ** [mwiede/jsch#205]
i need to stop the `SSH_MSG_SERVICE_REQUEST` from being sent to the server because of:

```
Once a party has sent a SSH_MSG_KEXINIT message for key exchange or
   re-exchange, until it has sent a SSH_MSG_NEWKEYS message (Section
   7.3), it MUST NOT send any messages other than:

   o  Transport layer generic messages (1 to 19) (but
      SSH_MSG_SERVICE_REQUEST and SSH_MSG_SERVICE_ACCEPT MUST NOT be
      sent);
```

**Comment by norrisjeremy** [comment]
Hi @ThnksCJ,

Can you provide more details on the circumstances in which you are seeing JSch sending an `SSH_MSG_SERVICE_REQUEST` message after `SSH_MSG_KEXINIT` but before `SSH_MSG_NEWKEYS`?

Thanks,
Jeremy

**Comment by ThnksCJ** [comment]
Thanks you replying @norrisjeremy but what your saying isn't exactly my issue, my issue is that I don't want it to send the `SSH_MSG_SERVICE_REQUEST` at all but it does. Is there anyway to not send it to the server because in source of jsch there is a UserAuthNone file and in it contains the code to sent these packets.

I hope to hear from you soon,
CJ Stevenson

**Comment by norrisjeremy** [comment]
Hi @ThnksCJ,

There currently isn't a way to prevent it from sending these messages.
We would need to develop a new feature (likely a new config option) to support this use case.

Thanks,
Jeremy

**Comment by ThnksCJ** [comment]
Hey @norrisjeremy 

Would it be too much to ask for you to implement it because I believe it it would be fairly simple and I would do it myself but I can't get the package to compile on my end

Thanks,
CJ Stevenson

**Comment by norrisjeremy** [comment]
Hi @ThnksCJ,

I can try to develop a PR for this, but it may take me a week or two to find some time.

Thanks,
Jeremy

**Comment by ThnksCJ** [comment]
Hey @norrisjeremy 

Hmm, could you tell me how to package my own because I could do it later as I need it sooner rather than later. When I tried compiling it I got errors and don't know why.

Thanks,
CJ Stevenson

**Comment by norrisjeremy** [comment]
Hi @ThnksCJ,

Were you building with Java 16 or newer? That is a requirement for building it with `mvn package`.

Thanks,
Jeremy

**Comment by ThnksCJ** [comment]
Hey @norrisjeremy 

If I'm being honest I'm not sure, I'll look tomorrow and see. I'll be in touch.

Thanks,
CJ Stevenson

**Comment by ThnksCJ** [comment]
Hello @norrisjeremy 

Ive checked and ive been building with java 17 and get the error `Cannot find project Scala library 2.13.6 for module jsch` when trying to sync the maven build. Any ideas?

Thanks,
CJ Stevenson

**Comment by norrisjeremy** [comment]
Hi @ThnksCJ,

What maven command are you executing?

Thanks,
Jeremy

**Comment by norrisjeremy** [comment]
Hi @ThnksCJ,

It looks like your IntelliJ isn't configured with a Java 16+ JVM. You'll need to investigate the settings.

Thanks,
Jeremy

**Comment by ThnksCJ** [comment]
Back again @norrisjeremy

My session seems to crash after sending/receiving `SSH_MSG_NEWKEYS ` do you know a fix for this?

Thanks,
CJ Stevenson

**Comment by norrisjeremy** [comment]
Hi @ThnksCJ,

Can you provide more details? Was this with released version of JSch from Maven Central, or was this with a version you modified to not send `SSH_MSG_SERVICE_REQUEST`s?
Do you have a stacktrace from an Exception that you can share? Or logging from JSch?

Thanks,
Jeremy
