### ISSUE TITLE
JSCH inside Maven itself

### ISSUE THREAD

**Issue by fbgihu** [mwiede/jsch#211]
I'm neither expert in maven nor in those ssh-key things. I use them as they work. I realized short time ago, that RSA is deprecated and switched my PC and Raspberries to ED25519 and that worked fine. I'm able to ssh between the machines and all works.
Now I went back to my formerly working maven construct. I'm developing on a linux PC and "maven install" puts the results to the Raspberry...worked fine. Now I receive an error id_rsa not found, which is correct, since it is replaced by id_ed25519. After correcting the ini-file, I receive "...build.xml:109: com.jcraft.jsch.JSchException: invalid privatekey: [B@5d..."
Dr. Google pointed me to your fork.
Your fork might be a drop-in-replacement, but if I put it in my maven dependencies it works for possible JSCH-connections within my programs?! But I need to replace the JSCH, which maven is using itself to push the build targets to the target machine. Hence to my understanding, the JSCH inside maven itself has to be replaced by your fork.
Is that understanding correct?
Any idea how to achieve that or if maven is going to be "ED25519-enabled"?
Thanks a lot for your work and maybe an answer.

**Comment by mwiede** [comment]
can you show, how your pom.xml looks like?

it should contain

```
<dependency>
  <groupId>com.github.mwiede</groupId>
  <artifactId>jsch</artifactId>
  <version>0.2.4</version>
</dependency>
```
if you use Jsch as a direct dependency  and 

```
<dependency>
  <groupId>com.github.mwiede</groupId>
  <artifactId>jsch</artifactId>
  <version>0.2.4</version>
</dependency>
<dependency>
  <groupId>foo</groupId>
  <artifactId>bar</artifactId>
  <exclusions>
        <exclusion>  
          <groupId>com.jcraft</groupId>
          <artifactId>jsch</artifactId>
        </exclusion>
      </exclusions> 
</dependency>
```
if you have a dependy foo:bar, where jsch is a transitive dependency.

you have to make sure, that only `com.github.mwiede:jsch:0.2.4` is on your classpath (for example you can check the output of `mvn dependency:tree`) and no `com.jcraft:jsch` any more.

Then the next question is, what java version you use. If you use java < 15, you need to put [Bouncycastle dependency](https://search.maven.org/artifact/org.bouncycastle/bcprov-jdk18on/1.71.1/jar) on your classpath to make ed25519 work. with higher java versions, it works without Bouncycastle.

**Comment by fbgihu** [comment]
I do not have any Jsch in the dependency tree, since I don't need it. Jsch is used only by maven itself to deploy build results on the target environment. Hence to my understanding it is irrelevant, what i put in my dependency tree, since that only affects my build result but not the way Maven pushes my build result to a target environment. Maybe I'm wrong. I've solved the problem for now by using an ecdsa keyfile, which is understood by maven's built-in Jsch.

**Comment by mwiede** [comment]
got it. I would be interesting to know, which maven-plugin is using jsch. Is there any log, where you can see, which maven plugin does the actual _deploy_ of yours? Maybe [Waggon](https://maven.apache.org/wagon/)?

Still, you can also influence plugin dependencies by the same mechanism as above.

**Comment by fbgihu** [comment]
No. Log only says  "...build.xml:109: com.jcraft.jsch.JSchException: invalid privatekey: [B@5d..."
Excerpt from build.xml:
```
        <macrodef name="copywithkey" uri="http://www.netbeans.org/ns/j2se-project/remote-platform/1">
            <attribute name="additionaljvmargs" default=""/>
            <sequential>
line 109:       <sshexec host="${target.platform.host}" port="${target.platform.port}" username="${target.platform.username}" keyfile="${target.platform.privatekey}" passphrase="${target.platform.passphrase}" trust="true" command="mkdir -p '${remote.dist.dir}'"/>
                <scp todir="${target.platform.username}@${target.platform.host}:${remote.dist.dir}" port="${target.platform.port}" keyfile="${target.platform.privatekey}" passphrase="${target.platform.passphrase}" trust="true">
                    <fileset dir="${local.dist.dir}">
                        <include name="*.${project.packaging}"/>
                        <include name="lib/*.${project.packaging}"/>
                    </fileset>
                </scp>
            </sequential>
        </macrodef>
```

**Comment by mwiede** [comment]
looks like you are using ant with [sshexec task](https://ant.apache.org/manual/Tasks/sshexec.html). Are you invoking this by a maven plugin?
like  
```xml
<plugin>
        <artifactId>maven-antrun-plugin</artifactId>
        <version>3.1.0</version>
        <executions>
          <execution>...
```
if yes, you should play around with the dependencies of this maven plugin like [someone on SO](https://stackoverflow.com/a/36762436/2290153)
