### ISSUE TITLE
Index out of bounds error with JSCH latest 0.2.4/0.2.1

### ISSUE THREAD

**Issue by mvharsha** [mwiede/jsch#228]
I have upgraded  to latest JSCH jar version 0.2.4 recently .
Connection to SFTP server from the client and transfer of files was happening successfully.
When reading and writing files continuously in a loop the file writing breaks with index out of bounds error.  It happens if there are say more than 100 files need to be transferred.

Error is below :

java.lang.ArrayIndexOutOfBoundsException: arraycopy: last destination index 26282 out of bounds for byte[20480]
	at java.lang.System.arraycopy(Native Method) 
	at com.jcraft.jsch.Buffer.putByte(Buffer.java:55) 
	at com.jcraft.jsch.Buffer.putString(Buffer.java:63) 
	at com.jcraft.jsch.Buffer.putString(Buffer.java:59) 
	at com.jcraft.jsch.Session.send_kexinit(Session.java:807) 
	at com.jcraft.jsch.Session.connect(Session.java:321) 

Can you please suggest possible root cause of this error and is that known already ?

**Comment by norrisjeremy** [comment]
Hi @mvharsha,

Can you share your code that leads to this exception occurring?

Also, can you enable logging in JSch and capture debug level logs, providing those as well?
This can be done by adding `JSch.setLogger(...)` somewhere in your application before calling `JSch.getSession()`. There are a few built-in logger implementations you can use, depending upon what type of logging framework you are using, such as `new JulLogger()`, `new Log4j2Logger()`, `new Slf4jLogger()` or `new JplLogger()`.

Thanks,
Jeremy

**Comment by mvharsha** [comment]
Hi @norrisjeremy 

Please find the Jsch logs below .
[Jsch_logs.txt](https://github.com/mwiede/jsch/files/9765031/Jsch_logs.txt)

**Comment by norrisjeremy** [comment]
Hi @mvharsha,

I see this in the logs:
```
	Line 34583: DEBUG 12.10.22 11:12:14,453 [IS-N1--MThread-12] JschSFTPLogger            INFO: KeyExchange: client: diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,di ...
	Line 34584: DEBUG 12.10.22 11:12:14,453 [IS-N1--MThread-12] JschSFTPLogger            INFO: KeyExchange: client: ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa ...
```

I believe you have a bug somewhere in your application in which you are continually executing something like this over and over (likely in a loop somewhere):
```
JSch.setConfig("kex", "diffie-hellman-group1-sha1,diffie-hellman-group14-sha1," + JSch.getConfig("kex"));
JSch.setConfig("server_host_key", "ssh-rsa,ssh-dss," + JSch.getConfig("server_host_key");
```

By repeatedly prepending these strings to the JSch `kex` & `server_host_key` configs, they grow ever larger, eventually causing it overflow the size of JSch's internal buffer.

I would recommend restructuring you application such that you only execute the `JSch.setConfig("kex", ...)` & `JSch.setConfig("server_host_key", ...)` methods a single time.

Thanks,
Jeremy

**Comment by mvharsha** [comment]
Thank you , I will check with this possibility and let you know if it works

**Comment by mvharsha** [comment]
> Hi @mvharsha,
> 
> I see this in the logs:
> 
> ```
> 	Line 34583: DEBUG 12.10.22 11:12:14,453 [IS-N1--MThread-12] JschSFTPLogger            INFO: KeyExchange: client: diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,di ...
> 	Line 34584: DEBUG 12.10.22 11:12:14,453 [IS-N1--MThread-12] JschSFTPLogger            INFO: KeyExchange: client: ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa,ssh-dss,ssh-rsa ...
> ```
> 
> I believe you have a bug somewhere in your application in which you are continually executing something like this over and over (likely in a loop somewhere):
> 
> ```
> JSch.setConfig("kex", "diffie-hellman-group1-sha1,diffie-hellman-group14-sha1," + JSch.getConfig("kex"));
> JSch.setConfig("server_host_key", "ssh-rsa,ssh-dss," + JSch.getConfig("server_host_key");
> ```
> 
> By repeatedly prepending these strings to the JSch `kex` & `server_host_key` configs, they grow ever larger, eventually causing it overflow the size of JSch's internal buffer.
> 
> I would recommend restructuring you application such that you only execute the `JSch.setConfig("kex", ...)` & `JSch.setConfig("server_host_key", ...)` methods a single time.
> 
> Thanks, Jeremy

This works fine , thanks for the quick reply
