### ISSUE TITLE
Algorithm negotiation fail

### ISSUE THREAD

**Issue by ytzyangting** [mwiede/jsch#231]
The algorithm negotiation fail. How to modify it according to the error message，
Thank you！

`Algorithm negotiation fail: algorithmName="kex" jschProposal="curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,ext-info-c" serverProposal="diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1"`

**Comment by mwiede** [comment]
Do you have access to the server? It's using weak algorithms see https://github.blog/2017-02-27-crypto-deprecation-notice/

If you can't change the server you can modify default jsch configuration as in #37
