### ISSUE TITLE
java.lang.ClassNotFoundException: DiffieHellman

### ISSUE THREAD

**Issue by iss96** [mwiede/jsch#240]
I am getting the below error while connecting to other server using JSch,
I used the below version in pom file

com.github.mwiede jsch 0.1.58
This Jenkins job started failing all of sudden due to the below error,
Please help...
Thanks in advance
Satya

----------Error------------------
java.lang.ClassNotFoundException: DiffieHellman
01:22:20 at org.codehaus.mojo.exec.URLClassLoaderBuilder$ExecJavaClassLoader.loadClass(URLClassLoaderBuilder.java:198)
01:22:20 at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
01:22:20 at java.lang.Class.forName0(Native Method)
01:22:20 at java.lang.Class.forName(Class.java:264)
01:22:20 at javax.crypto.Support.getImplementation(Support.java:77)
01:22:20 at javax.crypto.Support.getImplementation(Support.java:32)
01:22:20 at javax.crypto.KeyAgreement.getInstance(KeyAgreement.java:50)
01:22:20 at com.jcraft.jsch.jce.DH.init(DH.java:51)
01:22:20 at com.jcraft.jsch.DHG14.init(DHG14.java:111)
01:22:20 at com.jcraft.jsch.Session.checkKex(Session.java:2542)
01:22:20 at com.jcraft.jsch.Session.checkKexes(Session.java:2519)
01:22:20 at com.jcraft.jsch.Session.send_kexinit(Session.java:634)
01:22:20 at com.jcraft.jsch.Session.connect(Session.java:307)
01:22:20 at com.jcraft.jsch.Session.connect(Session.java:183)
01:22:20 at com.rsa.sid.agents.core.remote.SSHUtils.connect(SSHUtils.java:91)
01:22:20 at com.rsa.sid.agents.pam.AMRemoteJarUtil.getAMClientProperties(AMRemoteJarUtil.java:88)
01:22:20 at com.rsa.sid.agents.pam.AMRemoteJarUtil.updateConfig(AMRemoteJarUtil.java:77)
01:22:20 at com.rsa.sid.agents.pam.AMRemoteJarUtil.main(AMRemoteJarUtil.java:73)
01:22:20 at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:279)
01:22:20 at java.lang.Thread.run(Thread.java:748)
01:22:20 java.lang.ClassNotFoundException: ECDH
01:22:20 at org.codehaus.mojo.exec.URLClassLoaderBuilder$ExecJavaClassLoader.loadClass(URLClassLoaderBuilder.java:198)
01:22:20 at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
01:22:20 at java.lang.Class.forName0(Native Method)
01:22:20 at java.lang.Class.forName(Class.java:264)
01:22:20 at javax.crypto.Support.getImplementation(Support.java:77)
01:22:20 at javax.crypto.Support.getImplementation(Support.java:32)
01:22:20 at javax.crypto.KeyAgreement.getInstance(KeyAgreement.java:50)
01:22:20 at com.jcraft.jsch.jce.ECDHN.init(ECDHN.java:44)
01:22:20 at com.jcraft.jsch.DHECN.init(DHECN.java:81)
01:22:20 at com.jcraft.jsch.Session.checkKex(Session.java:2542)
01:22:20 at com.jcraft.jsch.Session.checkKexes(Session.java:2519)
01:22:20 at com.jcraft.jsch.Session.send_kexinit(Session.java:634)
01:22:20 at com.jcraft.jsch.Session.connect(Session.java:307)
01:22:20 at com.jcraft.jsch.Session.connect(Session.java:183)
01:22:20 at com.rsa.sid.agents.core.remote.SSHUtils.connect(SSHUtils.java:91)
01:22:20 at com.rsa.sid.agents.pam.AMRemoteJarUtil.getAMClientProperties(AMRemoteJarUtil.java:88)
01:22:20 at com.rsa.sid.agents.pam.AMRemoteJarUtil.updateConfig(AMRemoteJarUtil.java:77)
01:22:20 at com.rsa.sid.agents.pam.AMRemoteJarUtil.main(AMRemoteJarUtil.java:73)
01:22:20 at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:279)
01:22:20 at java.lang.Thread.run(Thread.java:748)
01:22:20 java.lang.ClassNotFoundException: ECDH
01:22:20 at org.codehaus.mojo.exec.URLClassLoaderBuilder$ExecJavaClassLoader.loadClass(URLClassLoaderBuilder.java:198)
01:22:20 at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
01:22:20 at java.lang.Class.forName0(Native Method)
01:22:20 at java.lang.Class.forName(Class.java:264)
01:22:20 at javax.crypto.Support.getImplementation(Support.java:77)
01:22:20 at javax.crypto.Support.getImplementation(Support.java:32)
01:22:20 at javax.crypto.KeyAgreement.getInstance(KeyAgreement.java:50)
01:22:20 at com.jcraft.jsch.jce.ECDHN.init(ECDHN.java:44)
01:22:20 at com.jcraft.jsch.DHECN.init(DHECN.java:81)
01:22:20 at com.jcraft.jsch.Session.checkKex(Session.java:2542)
01:22:20 at com.jcraft.jsch.Session.checkKexes(Session.java:2519)
01:22:20 at com.jcraft.jsch.Session.send_kexinit(Session.java:634)
01:22:20 at com.jcraft.jsch.Session.connect(Session.java:307)
01:22:20 at com.jcraft.jsch.Session.connect(Session.java:183)
01:22:20 at com.rsa.sid.agents.core.remote.SSHUtils.connect(SSHUtils.java:91)
01:22:20 at com.rsa.sid.agents.pam.AMRemoteJarUtil.getAMClientProperties(AMRemoteJarUtil.java:88)
01:22:20 at com.rsa.sid.agents.pam.AMRemoteJarUtil.updateConfig(AMRemoteJarUtil.java:77)
01:22:20 at com.rsa.sid.agents.pam.AMRemoteJarUtil.main(AMRemoteJarUtil.java:73)
01:22:20 at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:279)
01:22:20 at java.lang.Thread.run(Thread.java:748)
01:22:20 java.lang.ClassNotFoundException: ECDH
01:22:20 at org.codehaus.mojo.exec.URLClassLoaderBuilder$ExecJavaClassLoader.loadClass(URLClassLoaderBuilder.java:198)
01:22:20 at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
01:22:20 at java.lang.Class.forName0(Native Method)
01:22:20 at java.lang.Class.forName(Class.java:264)
01:22:20 at javax.crypto.Support.getImplementation(Support.java:77)
01:22:20 at javax.crypto.Support.getImplementation(Support.java:32)
01:22:20 at javax.crypto.KeyAgreement.getInstance(KeyAgreement.java:50)
01:22:20 at com.jcraft.jsch.jce.ECDHN.init(ECDHN.java:44)
01:22:20 at com.jcraft.jsch.DHECN.init(DHECN.java:81)
01:22:20 at com.jcraft.jsch.Session.checkKex(Session.java:2542)
01:22:20 at com.jcraft.jsch.Session.checkKexes(Session.java:2519)
01:22:20 at com.jcraft.jsch.Session.send_kexinit(Session.java:634)
01:22:20 at com.jcraft.jsch.Session.connect(Session.java:307)
01:22:20 at com.jcraft.jsch.Session.connect(Session.java:183)
01:22:20 at com.rsa.sid.agents.core.remote.SSHUtils.connect(SSHUtils.java:91)
01:22:20 at com.rsa.sid.agents.pam.AMRemoteJarUtil.getAMClientProperties(AMRemoteJarUtil.java:88)
01:22:20 at com.rsa.sid.agents.pam.AMRemoteJarUtil.updateConfig(AMRemoteJarUtil.java:77)
01:22:20 at com.rsa.sid.agents.pam.AMRemoteJarUtil.main(AMRemoteJarUtil.java:73)
01:22:20 at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:279)
01:22:20 at java.lang.Thread.run(Thread.java:748)
01:22:20 Caught and rethrew exception com.jcraft.jsch.JSchException. Failed attempt to SSH to 172.XX.XX.93 using username bobuser password mypass123$ port 22
01:22:20 [WARNING]
01:22:20 com.jcraft.jsch.JSchException: Algorithm negotiation fail
01:22:20 at com.jcraft.jsch.Session.receive_kexinit (Session.java:590)
01:22:20 at com.jcraft.jsch.Session.connect (Session.java:320)
01:22:20 at com.jcraft.jsch.Session.connect (Session.java:183)
01:22:20 at com.rsa.sid.agents.core.remote.SSHUtils.connect (SSHUtils.java:91)
01:22:20 at com.rsa.sid.agents.pam.AMRemoteJarUtil.getAMClientProperties (AMRemoteJarUtil.java:88)
01:22:20 at com.rsa.sid.agents.pam.AMRemoteJarUtil.updateConfig (AMRemoteJarUtil.java:77)
01:22:20 at com.rsa.sid.agents.pam.AMRemoteJarUtil.main (AMRemoteJarUtil.java:73)
01:22:20 at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:279)
01:22:20 at java.lang.Thread.run (Thread.java:748)

**Comment by mwiede** [comment]
hi @iss96 any reason why you are using such an old version?

the stacktrace is not helping, better you show the output of Jsch logger.

**Comment by iss96** [comment]
Thanks for the help,
As you requested, pasting the output from the Jsch Logger. I tried updating my pom file to the 0.2.4 jsch version too, but it's not still using Jsch-0.1.54, this code is in working condition 3 months back, but when I tried to execute the Jenkins job for the last two days, it failed with the below error. 
------------------------------------
17:00:13 2022-11-13 17:00:13.013 +0530:[JSCH-LOGGER][INFO]:Connecting to 172.X.X.X port 22
17:00:13 2022-11-13 17:00:13.013 +0530:[JSCH-LOGGER][INFO]:Connection established
17:00:13 2022-11-13 17:00:13.013 +0530:[JSCH-LOGGER][INFO]:Remote version string: SSH-2.0-OpenSSH_7.2
17:00:13 2022-11-13 17:00:13.013 +0530:[JSCH-LOGGER][INFO]:Local version string: SSH-2.0-JSCH-0.1.54
17:00:13 2022-11-13 17:00:13.013 +0530:[JSCH-LOGGER][INFO]:CheckCiphers: aes256-ctr,aes192-ctr,aes128-ctr,aes256-cbc,aes192-cbc,aes128-cbc,3des-ctr,arcfour,arcfour128,arcfour256
17:00:14 2022-11-13 17:00:14.014 +0530:[JSCH-LOGGER][INFO]:aes256-ctr is not available.
17:00:14 2022-11-13 17:00:14.014 +0530:[JSCH-LOGGER][INFO]:aes192-ctr is not available.
17:00:14 2022-11-13 17:00:14.014 +0530:[JSCH-LOGGER][INFO]:aes128-ctr is not available.
17:00:14 2022-11-13 17:00:14.014 +0530:[JSCH-LOGGER][INFO]:aes256-cbc is not available.
17:00:14 2022-11-13 17:00:14.014 +0530:[JSCH-LOGGER][INFO]:aes192-cbc is not available.
17:00:14 2022-11-13 17:00:14.014 +0530:[JSCH-LOGGER][INFO]:aes128-cbc is not available.
17:00:14 2022-11-13 17:00:14.014 +0530:[JSCH-LOGGER][INFO]:3des-ctr is not available.
17:00:14 2022-11-13 17:00:14.014 +0530:[JSCH-LOGGER][INFO]:CheckKexes: diffie-hellman-group14-sha1,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521
17:00:14 java.lang.ClassNotFoundException: DiffieHellman
17:00:14 	at org.codehaus.mojo.exec.URLClassLoaderBuilder$ExecJavaClassLoader.loadClass(URLClassLoaderBuilder.java:198)
17:00:14 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
17:00:14 	at java.lang.Class.forName0(Native Method)
17:00:14 	at java.lang.Class.forName(Class.java:264)
17:00:14 	at javax.crypto.Support.getImplementation(Support.java:77)
17:00:14 	at javax.crypto.Support.getImplementation(Support.java:32)
17:00:14 	at javax.crypto.KeyAgreement.getInstance(KeyAgreement.java:50)
17:00:14 	at com.jcraft.jsch.jce.DH.init(DH.java:51)
17:00:14 	at com.jcraft.jsch.DHG14.init(DHG14.java:111)
17:00:14 	at com.jcraft.jsch.Session.checkKex(Session.java:2542)
17:00:14 	at com.jcraft.jsch.Session.checkKexes(Session.java:2519)
17:00:14 	at com.jcraft.jsch.Session.send_kexinit(Session.java:634)
17:00:14 	at com.jcraft.jsch.Session.connect(Session.java:307)
17:00:14 	at com.jcraft.jsch.Session.connect(Session.java:183)
17:00:14 	at com.rsa.sid.agents.core.remote.SSHUtils.connect(SSHUtils.java:92)
17:00:14 	at com.rsa.sid.agents.pam.AMRemoteJarUtil.getAMClientProperties(AMRemoteJarUtil.java:88)
17:00:14 	at com.rsa.sid.agents.pam.AMRemoteJarUtil.updateConfig(AMRemoteJarUtil.java:77)
17:00:14 	at com.rsa.sid.agents.pam.AMRemoteJarUtil.main(AMRemoteJarUtil.java:73)
17:00:14 	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:279)
17:00:14 	at java.lang.Thread.run(Thread.java:748)
17:00:14 java.lang.ClassNotFoundException: ECDH
17:00:14 	at org.codehaus.mojo.exec.URLClassLoaderBuilder$ExecJavaClassLoader.loadClass(URLClassLoaderBuilder.java:198)
17:00:14 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
17:00:14 	at java.lang.Class.forName0(Native Method)
17:00:14 	at java.lang.Class.forName(Class.java:264)
17:00:14 	at javax.crypto.Support.getImplementation(Support.java:77)
17:00:14 	at javax.crypto.Support.getImplementation(Support.java:32)
17:00:14 	at javax.crypto.KeyAgreement.getInstance(KeyAgreement.java:50)
17:00:14 	at com.jcraft.jsch.jce.ECDHN.init(ECDHN.java:44)
17:00:14 	at com.jcraft.jsch.DHECN.init(DHECN.java:81)
17:00:14 	at com.jcraft.jsch.Session.checkKex(Session.java:2542)
17:00:14 	at com.jcraft.jsch.Session.checkKexes(Session.java:2519)
17:00:14 	at com.jcraft.jsch.Session.send_kexinit(Session.java:634)
17:00:14 	at com.jcraft.jsch.Session.connect(Session.java:307)
17:00:14 	at com.jcraft.jsch.Session.connect(Session.java:183)
17:00:14 	at com.rsa.sid.agents.core.remote.SSHUtils.connect(SSHUtils.java:92)
17:00:14 	at com.rsa.sid.agents.pam.AMRemoteJarUtil.getAMClientProperties(AMRemoteJarUtil.java:88)
17:00:14 	at com.rsa.sid.agents.pam.AMRemoteJarUtil.updateConfig(AMRemoteJarUtil.java:77)
17:00:14 	at com.rsa.sid.agents.pam.AMRemoteJarUtil.main(AMRemoteJarUtil.java:73)
17:00:14 	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:279)
17:00:14 	at java.lang.Thread.run(Thread.java:748)
17:00:14 java.lang.ClassNotFoundException: ECDH
17:00:14 	at org.codehaus.mojo.exec.URLClassLoaderBuilder$ExecJavaClassLoader.loadClass(URLClassLoaderBuilder.java:198)
17:00:14 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
17:00:14 	at java.lang.Class.forName0(Native Method)
17:00:14 	at java.lang.Class.forName(Class.java:264)
17:00:14 	at javax.crypto.Support.getImplementation(Support.java:77)
17:00:14 	at javax.crypto.Support.getImplementation(Support.java:32)
17:00:14 	at javax.crypto.KeyAgreement.getInstance(KeyAgreement.java:50)
17:00:14 	at com.jcraft.jsch.jce.ECDHN.init(ECDHN.java:44)
17:00:14 	at com.jcraft.jsch.DHECN.init(DHECN.java:81)
17:00:14 	at com.jcraft.jsch.Session.checkKex(Session.java:2542)
17:00:14 	at com.jcraft.jsch.Session.checkKexes(Session.java:2519)
17:00:14 	at com.jcraft.jsch.Session.send_kexinit(Session.java:634)
17:00:14 	at com.jcraft.jsch.Session.connect(Session.java:307)
17:00:14 	at com.jcraft.jsch.Session.connect(Session.java:183)
17:00:14 	at com.rsa.sid.agents.core.remote.SSHUtils.connect(SSHUtils.java:92)
17:00:14 	at com.rsa.sid.agents.pam.AMRemoteJarUtil.getAMClientProperties(AMRemoteJarUtil.java:88)
17:00:14 	at com.rsa.sid.agents.pam.AMRemoteJarUtil.updateConfig(AMRemoteJarUtil.java:77)
17:00:14 	at com.rsa.sid.agents.pam.AMRemoteJarUtil.main(AMRemoteJarUtil.java:73)
17:00:14 	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:279)
17:00:14 	at java.lang.Thread.run(Thread.java:748)
17:00:14 java.lang.ClassNotFoundException: ECDH
17:00:14 	at org.codehaus.mojo.exec.URLClassLoaderBuilder$ExecJavaClassLoader.loadClass(URLClassLoaderBuilder.java:198)
17:00:14 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
17:00:14 	at java.lang.Class.forName0(Native Method)
17:00:14 	at java.lang.Class.forName(Class.java:264)
17:00:14 	at javax.crypto.Support.getImplementation(Support.java:77)
17:00:14 	at javax.crypto.Support.getImplementation(Support.java:32)
17:00:14 	at javax.crypto.KeyAgreement.getInstance(KeyAgreement.java:50)
17:00:14 	at com.jcraft.jsch.jce.ECDHN.init(ECDHN.java:44)
17:00:14 	at com.jcraft.jsch.DHECN.init(DHECN.java:81)
17:00:14 	at com.jcraft.jsch.Session.checkKex(Session.java:2542)
17:00:14 	at com.jcraft.jsch.Session.checkKexes(Session.java:2519)
17:00:14 	at com.jcraft.jsch.Session.send_kexinit(Session.java:634)
17:00:14 	at com.jcraft.jsch.Session.connect(Session.java:307)
17:00:14 	at com.jcraft.jsch.Session.connect(Session.java:183)
17:00:14 	at com.rsa.sid.agents.core.remote.SSHUtils.connect(SSHUtils.java:92)
17:00:14 	at com.rsa.sid.agents.pam.AMRemoteJarUtil.getAMClientProperties(AMRemoteJarUtil.java:88)
17:00:14 	at com.rsa.sid.agents.pam.AMRemoteJarUtil.updateConfig(AMRemoteJarUtil.java:77)
17:00:14 	at com.rsa.sid.agents.pam.AMRemoteJarUtil.main(AMRemoteJarUtil.java:73)
17:00:14 	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:279)
17:00:14 	at java.lang.Thread.run(Thread.java:748)
17:00:14 2022-11-13 17:00:14.014 +0530:[JSCH-LOGGER][INFO]:diffie-hellman-group14-sha1 is not available.
17:00:14 2022-11-13 17:00:14.014 +0530:[JSCH-LOGGER][INFO]:ecdh-sha2-nistp256 is not available.
17:00:14 2022-11-13 17:00:14.014 +0530:[JSCH-LOGGER][INFO]:ecdh-sha2-nistp384 is not available.
17:00:14 2022-11-13 17:00:14.014 +0530:[JSCH-LOGGER][INFO]:ecdh-sha2-nistp521 is not available.
17:00:14 2022-11-13 17:00:14.014 +0530:[JSCH-LOGGER][INFO]:CheckSignatures: ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
17:00:14 2022-11-13 17:00:14.014 +0530:[JSCH-LOGGER][INFO]:SSH_MSG_KEXINIT sent
17:00:14 2022-11-13 17:00:14.014 +0530:[JSCH-LOGGER][INFO]:SSH_MSG_KEXINIT received
17:00:14 2022-11-13 17:00:14.014 +0530:[JSCH-LOGGER][INFO]:kex: server: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,curve25519-sha256@libssh.org
17:00:14 2022-11-13 17:00:14.014 +0530:[JSCH-LOGGER][INFO]:kex: server: ecdsa-sha2-nistp256
17:00:14 2022-11-13 17:00:14.014 +0530:[JSCH-LOGGER][INFO]:kex: server: aes128-ctr,aes192-ctr,aes256-ctr,chacha20-poly1305@openssh.com
17:00:14 2022-11-13 17:00:14.014 +0530:[JSCH-LOGGER][INFO]:kex: server: aes128-ctr,aes192-ctr,aes256-ctr,chacha20-poly1305@openssh.com
17:00:14 2022-11-13 17:00:14.014 +0530:[JSCH-LOGGER][INFO]:kex: server: hmac-sha2-256,hmac-sha2-512,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com
17:00:14 2022-11-13 17:00:14.014 +0530:[JSCH-LOGGER][INFO]:kex: server: hmac-sha2-256,hmac-sha2-512,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com
17:00:14 2022-11-13 17:00:14.014 +0530:[JSCH-LOGGER][INFO]:kex: server: none,zlib@openssh.com
17:00:14 2022-11-13 17:00:14.014 +0530:[JSCH-LOGGER][INFO]:kex: server: none,zlib@openssh.com
17:00:14 2022-11-13 17:00:14.014 +0530:[JSCH-LOGGER][INFO]:kex: server: 
17:00:14 2022-11-13 17:00:14.014 +0530:[JSCH-LOGGER][INFO]:kex: server: 
17:00:14 2022-11-13 17:00:14.014 +0530:[JSCH-LOGGER][INFO]:kex: client: diffie-hellman-group1-sha1,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1
17:00:14 2022-11-13 17:00:14.014 +0530:[JSCH-LOGGER][INFO]:kex: client: ssh-rsa,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
17:00:14 2022-11-13 17:00:14.014 +0530:[JSCH-LOGGER][INFO]:kex: client: 3des-cbc,blowfish-cbc
17:00:14 2022-11-13 17:00:14.014 +0530:[JSCH-LOGGER][INFO]:kex: client: 3des-cbc,blowfish-cbc
17:00:14 2022-11-13 17:00:14.014 +0530:[JSCH-LOGGER][INFO]:kex: client: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha1-96,hmac-md5-96
17:00:14 2022-11-13 17:00:14.014 +0530:[JSCH-LOGGER][INFO]:kex: client: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha1-96,hmac-md5-96
17:00:14 2022-11-13 17:00:14.014 +0530:[JSCH-LOGGER][INFO]:kex: client: none
17:00:14 2022-11-13 17:00:14.014 +0530:[JSCH-LOGGER][INFO]:kex: client: none
17:00:14 2022-11-13 17:00:14.014 +0530:[JSCH-LOGGER][INFO]:kex: client: 
17:00:14 2022-11-13 17:00:14.014 +0530:[JSCH-LOGGER][INFO]:kex: client: 
17:00:14 2022-11-13 17:00:14.014 +0530:[JSCH-LOGGER][INFO]:Disconnecting from 172.X.X.X port 22
17:00:14 Caught and rethrew exception com.jcraft.jsch.JSchException.  Failed attempt to SSH to 172.X.X.X using username rsaadmin password mypassword$ port 22
17:00:14 [WARNING] 
17:00:14 com.jcraft.jsch.JSchException: Algorithm negotiation fail
17:00:14     at com.jcraft.jsch.Session.receive_kexinit (Session.java:590)
17:00:14     at com.jcraft.jsch.Session.connect (Session.java:320)
17:00:14     at com.jcraft.jsch.Session.connect (Session.java:183)
17:00:14     at com.rsa.sid.agents.core.remote.SSHUtils.connect (SSHUtils.java:92)
17:00:14     at com.rsa.sid.agents.pam.AMRemoteJarUtil.getAMClientProperties (AMRemoteJarUtil.java:88)
17:00:14     at com.rsa.sid.agents.pam.AMRemoteJarUtil.updateConfig (AMRemoteJarUtil.java:77)
17:00:14     at com.rsa.sid.agents.pam.AMRemoteJarUtil.main (AMRemoteJarUtil.java:73)
17:00:14     at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:279)
17:00:14     at java.lang.Thread.run (Thread.java:748)
-------------------------------------------------------------------------

**Comment by norrisjeremy** [comment]
Hi @iss96,

This appears to be from JSch release 0.1.54, which is an old release prior to this fork.
Additionally, something appears to be amiss with your Java installation, in that it is unable to locate Java Security Providers that can supply DiffieHellman & ECDH implementations.
I would suggest confirming that your Java installation is sound and whether you may be loading third party security providers that are interfering with JSch.

Thanks,
Jeremy

**Comment by iss96** [comment]
Can you help me to address your suggestions... 1) and 2)
1) Additionally, something appears to be amiss with your Java installation, in that it is unable to locate Java Security Providers that can supply DiffieHellman & ECDH implementations.
2) I would suggest confirming that your Java installation is sound and whether you may be loading third party security providers that are interfering with JSch.
how to check 1) and 2) ??

**Comment by norrisjeremy** [comment]
Hi @iss96,

Unfortunately, that is beyond my capability to troubleshoot and debug your environment.

Thanks,
Jeremy

**Comment by iss96** [comment]
Ok, let me look at my Java environment and Jenkins, Thanks for the support.
