### ISSUE TITLE
Add OSGI metadata to MANIFEST

### ISSUE THREAD

**Issue by zspitzer** [mwiede/jsch#248]
Would it be possible to add OSGI metadata to the Manifest?

I work on the Lucee project https://github.com/lucee/Lucee and we are currently using the old jsch lib and would like to switch to using this actively maintained fork https://luceeserver.atlassian.net/browse/LDEV-4299 

We've been wrapping up the old lib as an OSGI bundle (https://github.com/lucee/osgi-bundle-jsch), but it would be great if we could just use this one directly via maven

https://github.com/srikanth-lingala/zip4j/issues/89

**Comment by mwiede** [comment]
@zspitzer can you please try 0.2.5 release and verify that it suits your needs? Thanks

**Comment by zspitzer** [comment]
@mwiede danke! all working as expected
