### ISSUE TITLE
com.jcraft.jsch.JSchException: Session.connect: java.io.IOException: End of IO Stream Read

### ISSUE THREAD

**Issue by bofei222** [mwiede/jsch#25]
first ,thks for your improve.

Could you resolve my question?

i got
com.jcraft.jsch.JSchException: Session.connect: java.io.IOException: End of IO Stream Read
when I rewrite it myself

**Comment by norrisjeremy** [comment]
Hi, are there more details you can share?
Perhaps a full stack trace and some sample code that is failing for you?

**Comment by norrisjeremy** [comment]
Hi @bofei222,

Are you able to provide any additional details about the issue you are encountering?

Thanks,
Jeremy
