### ISSUE TITLE
Build is failing in ubuntu-22.04

### ISSUE THREAD

**Issue by mwiede** [mwiede/jsch#253]
As Github upgraded its runner image `ubuntu-latest` to `ubuntu-22.04` (see https://github.blog/changelog/2022-11-09-github-actions-ubuntu-latest-workflows-will-use-ubuntu-22-04/) the maven build is failing.

initially I thought it would be the same problem I recognized inside Github Codespace environment. Here the crucial part is that binding a file from `/tmp` does not work with docker.
But for Github Actions, it seems to be a different issue from underlying image upgrade.

**Comment by norrisjeremy** [comment]
In Ubuntu 22.04, the permissions of user home directories (`/home/xyz`) changed such that they are no longer world readable (i.e. they are  `drwxr-x---` / 750 instead of `drwxr-xr-x` / 755).
Do you think that could have been the issue?
