### ISSUE TITLE
Support for new KEX algorithms and ciphers

### ISSUE THREAD

**Issue by avnerw74** [mwiede/jsch#26]
Hi,

Thanks for all your improvements to JSCH.
I have a question/request for enhancement.
Are there any plans to support the following?

KexAlgorithms: 
1. curve25519-sha256@libssh.org
2. curve25519-sha256
3. diffie-hellman-group18-sha512
4. diffie-hellman-group16-sha512
5. diffie-hellman-group14-sha256

Ciphers: 
1. aes256-gcm@openssh.com

MACs: 
1. hmac-sha2-512-etm@openssh.com
2. hmac-sha2-256-etm@openssh.com

Thanks,
Avner

**Comment by mwiede** [comment]
They should already have been implemented with #4.
Some are only available with java version >= 11

Can you please verify that it works for you?

**Comment by avnerw74** [comment]
Thanks @mwiede, I'll check it.
