### ISSUE TITLE
Algorithm negotiation failure

### ISSUE THREAD

**Issue by wise-coders** [mwiede/jsch#263]
With the latest library, I got this error. Which could be the reason?

Algorithm negotiation fail: algorithmName="server_host_key" jschProposal="ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256" serverProposal="ssh-rsa,ssh-dss"
SSH Tunnel Exception: com.jcraft.jsch.JSchAlgoNegoFailException: Algorithm negotiation fail: algorithmName="server_host_key" jschProposal="ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256" serverProposal="ssh-rsa,ssh-dss"

**Comment by jgolda** [comment]
(Disclaimer: I'm not a maintainer, just a fellow user of JSch, accidentally wandered to this issue :P )

Looks like there is no common algorithm which could be used by both the client (jsch) and server. I'd start with either enabling in JSch one of the algorithms required by the server or the other way round - enabling in the server one of the algorithms supported by JSch, depending on which is easier for you

**Comment by norrisjeremy** [comment]
Yes, please see the [FAQ](https://github.com/mwiede/jsch#why-do-ssh-rsa-type-keys-not-work-with-this-jsch-fork-and-my-server).
