### ISSUE TITLE
private key auth failure

### ISSUE THREAD

**Issue by ivanpedruzzi** [mwiede/jsch#271]
We are investigating an authorization failure using private key, this is the full log.

We are running version jsch-0.2.5.jar.

Do you spot anything that can point us into the right direction?

message: Connection established
message: Remote version string: SSH-2.0-SFTPPlus
message: Local version string: SSH-2.0-JSCH_0.2.5
message: CheckCiphers: chacha20-poly1305@openssh.com
message: CheckKexes: curve25519-sha256,curve25519-sha256@libssh.org,curve448-sha512
message: curve25519-sha256 is not available.
message: curve25519-sha256@libssh.org is not available.
message: curve448-sha512 is not available.

message: kex proposal before removing unavailable algos is: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256
message: kex proposal after removing unavailable algos is: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256

message: CheckSignatures: ssh-ed25519,ssh-ed448
message: ssh-ed25519 is not available.
message: ssh-ed448 is not available.

message: server_host_key proposal before removing unavailable algos is: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss
message: server_host_key proposal after removing unavailable algos is: ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss
message: server_host_key proposal before known_host reordering is: ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss
message: server_host_key proposal after known_host reordering is: ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss

message: SSH_MSG_KEXINIT sent
message: SSH_MSG_KEXINIT received

message: kex: server: ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group15-sha512,diffie-hellman-group14-sha256
message: kex: server: ssh-rsa
message: kex: server: aes256-ctr,aes192-ctr,aes128-ctr
message: kex: server: aes256-ctr,aes192-ctr,aes128-ctr
message: kex: server: hmac-sha2-512,hmac-sha2-256
message: kex: server: hmac-sha2-512,hmac-sha2-256
message: kex: server: none,zlib
message: kex: server: none,zlib
message: kex: server: 
message: kex: server: 
message: kex: client: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,ext-info-c
message: kex: client: ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss
message: kex: client: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
message: kex: client: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
message: kex: client: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
message: kex: client: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
message: kex: client: none
message: kex: client: none
message: kex: client: 
message: kex: client: 
message: kex: algorithm: ecdh-sha2-nistp256
message: kex: host key algorithm: ssh-rsa
message: kex: server->client cipher: aes128-ctr MAC: hmac-sha2-256 compression: none
message: kex: client->server cipher: aes128-ctr MAC: hmac-sha2-256 compression: none

message: SSH_MSG_KEX_ECDH_INIT sent
message: expecting SSH_MSG_KEX_ECDH_REPLY
message: ssh_rsa_verify: ssh-rsa signature true
message: Permanently added 'sftp.di.siemens.com' (RSA) to the list of known hosts.

message: SSH_MSG_NEWKEYS sent
message: SSH_MSG_NEWKEYS received
message: SSH_MSG_SERVICE_REQUEST sent
message: SSH_MSG_SERVICE_ACCEPT received
message: Authentications that can continue: publickey,password
message: Next authentication method: publickey
PubkeyAcceptedAlgorithms = ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss

Signature algorithms unavailable for non-agent identities = [ssh-ed25519, ssh-ed448]

No server-sig-algs found, using PubkeyAcceptedAlgorithms = [ssh-ed25519, ecdsa-sha2-nistp256, ecdsa-sha2-nistp384, ecdsa-sha2-nistp521, rsa-sha2-512, rsa-sha2-256, ssh-rsa, ssh-dss]

message: rsa-sha2-512 preauth success
message: rsa-sha2-512 auth failure

message: Authentications that can continue: password
message: Next authentication method: password
message: Disconnecting from ...

**Comment by norrisjeremy** [comment]
Hi @ivanpedruzzi,

Are you using the same private key named `EETSiemensPrivateKey.ppk` with JSch?
If so, can you confirm whether the first line of that file has `PuTTY-User-Key-File-2` or `PuTTY-User-Key-File-3`?

Thanks,
Jeremy

**Comment by ivanpedruzzi** [comment]
Hello Jeremy, we use the same key, and the first line looks like this:

PuTTY-User-Key-File-2: ssh-rsa

**Comment by norrisjeremy** [comment]
Hi @ivanpedruzzi,

It may be that this particular server doesn't correctly support the `rsa-sha2-512` or `rsa-sha2-256` type authentication.
Can you try reordering the JSch config for `PubkeyAcceptedAlgorithms` to put `ssh-rsa` at the start of the list instead of the end of the list and see if that works?

Thanks,
Jeremy

**Comment by ivanpedruzzi** [comment]
it works if we force the following properties:

m_session.setConfig("server_host_key"                   , "ssh-rsa"); 
m_session.setConfig("PubkeyAcceptedAlgorithms", "ssh-rsa");

**Comment by ivanpedruzzi** [comment]
Thanks Jeremy, for your quick response, very much appreciated.

**Comment by norrisjeremy** [comment]
Hi @ivanpedruzzi,

Would you be able to test a build from my PR #264 from the below location and see if it works for you if when you don't hardcode JSch to only accept `ssh-rsa`?

https://github.com/mwiede/jsch/suites/10561053626/artifacts/525493489

Thanks,
Jeremy

**Comment by ivanpedruzzi** [comment]
Hello @norrisjeremy 

Unfortunately, it fails here is the log

message: Connecting to ..... port 22
message: Connection established
message: Remote version string: SSH-2.0-SFTPPlus
message: Local version string: SSH-2.0-JSCH_0.2.7_SNAPSHOT
message: CheckCiphers: chacha20-poly1305@openssh.com
message: CheckKexes: curve25519-sha256,curve25519-sha256@libssh.org,curve448-sha512
message: curve25519-sha256 is not available.
message: curve25519-sha256@libssh.org is not available.
message: curve448-sha512 is not available.
message: kex proposal before removing unavailable algos is: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256
message: kex proposal after removing unavailable algos is: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256
message: CheckSignatures: ssh-ed25519,ssh-ed448
message: ssh-ed25519 is not available.
message: ssh-ed448 is not available.
message: server_host_key proposal before removing unavailable algos is: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256
message: server_host_key proposal after removing unavailable algos is: ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256
message: server_host_key proposal before known_host reordering is: ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256
message: server_host_key proposal after known_host reordering is: ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256
message: SSH_MSG_KEXINIT sent
message: SSH_MSG_KEXINIT received
message: kex: server: ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group15-sha512,diffie-hellman-group14-sha256
message: kex: server: ssh-rsa
message: kex: server: aes256-ctr,aes192-ctr,aes128-ctr
message: kex: server: aes256-ctr,aes192-ctr,aes128-ctr
message: kex: server: hmac-sha2-512,hmac-sha2-256
message: kex: server: hmac-sha2-512,hmac-sha2-256
message: kex: server: none,zlib
message: kex: server: none,zlib
message: kex: server: 
message: kex: server: 
message: kex: client: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,ext-info-c
message: kex: client: ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256
message: kex: client: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
message: kex: client: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
message: kex: client: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
message: kex: client: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
message: kex: client: none
message: kex: client: none
message: kex: client: 
message: kex: client: 
message: Disconnecting from ..... port 22


Here what the organization hosting the SFTP server claims

Accepted SSH Cipher:

aes128-ctr
aes192-ctr
aes256-ctr          

Accepted Key Exchange (KEX) algorithms:

diffie-hellman-group-exchange-sha256
diffie-hellman-group14-sha256
diffie-hellman-group15-sha512
diffie-hellman-group16-sha512
ecdh-sha2-nistp256
ecdh-sha2-nistp384
ecdh-sha2-nistp521

Accepted Message Authentication Code (MAC) algorithms:
                
hmac-sha2-256
hmac-sha2-512

**Comment by ivanpedruzzi** [comment]
it seems they are using https://www.sftpplus.com/documentation/sftpplus/latest/configuration-server/ssh-service.html
Let me know if I can provide additional help to investigate.

**Comment by norrisjeremy** [comment]
Hi @ivanpedruzzi,

In your original logs, you had somehow added `ssh-rsa` near the end of the `server_host_key ` & `PubkeyAcceptedAlgorithms` configs in JSch:
```
message: kex: client: ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss
...
PubkeyAcceptedAlgorithms = ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss
```

Does it work if you go back to that setup (something like this)?

```
m_session.setConfig("server_host_key", m_session.getConfig("server_host_key") + ",ssh-rsa,ssh-dss");
m_session.setConfig("PubkeyAcceptedAlgorithms", m_session.getConfig("PubkeyAcceptedAlgorithms") + ",ssh-rsa,ssh-dss");
```

That's what I'm trying to ascertain whether this build fixes.
I.e., if JSch has `ssh-rsa` turned on like you had after `rsa-sha2-512,rsa-sha2-256`, will it attempt to login using `ssh-rsa` after the initial failure with `rsa-sha2-512` instead of failing to authenticate entirely using an RSA key.

Thanks!
Jeremy

**Comment by ivanpedruzzi** [comment]
@norrisjeremy,  we changed our configuration to have ssh-rsa,ssh-dss at the beginning of the list and it works.

        if(m_enable_legacy_algorithms) {
        	LogManager.getLogger().log(Level.FINEST, "enable_legacy_algorithms " + m_enable_legacy_algorithms);
        	m_session.setConfig("server_host_key"         , "ssh-rsa,ssh-dss," + m_session.getConfig("server_host_key")); 
        	m_session.setConfig("PubkeyAcceptedAlgorithms", "ssh-rsa,ssh-dss," + 
                m_session.getConfig("PubkeyAcceptedAlgorithms")); 
        }

**Comment by norrisjeremy** [comment]
Hi @ivanpedruzzi,

But what about if it's at the end of the lists, not the beginning of the lists, using this build?

Thanks,
Jeremy

**Comment by ivanpedruzzi** [comment]
@norrisjeremy, it seems to work.

Connecting to .... port 22
Connection established
Remote version string: SSH-2.0-SFTPPlus
Local version string: SSH-2.0-JSCH_0.2.7_SNAPSHOT
CheckCiphers: chacha20-poly1305@openssh.com
CheckKexes: curve25519-sha256,curve25519-sha256@libssh.org,curve448-sha512
curve25519-sha256 is not available.
curve25519-sha256@libssh.org is not available.
curve448-sha512 is not available.
kex proposal before removing unavailable algos is: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256
kex proposal after removing unavailable algos is: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256
CheckSignatures: ssh-ed25519,ssh-ed448
ssh-ed25519 is not available.
ssh-ed448 is not available.
server_host_key proposal before removing unavailable algos is: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss
server_host_key proposal after removing unavailable algos is: ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss
server_host_key proposal before known_host reordering is: ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss
server_host_key proposal after known_host reordering is: ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss
SSH_MSG_KEXINIT sent
SSH_MSG_KEXINIT received
kex: server: ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group15-sha512,diffie-hellman-group14-sha256
kex: server: ssh-rsa
kex: server: aes256-ctr,aes192-ctr,aes128-ctr
kex: server: aes256-ctr,aes192-ctr,aes128-ctr
kex: server: hmac-sha2-512,hmac-sha2-256
kex: server: hmac-sha2-512,hmac-sha2-256
kex: server: none,zlib
kex: server: none,zlib
kex: server: 
kex: server: 
kex: client: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,ext-info-c
kex: client: ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss
kex: client: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
kex: client: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
kex: client: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
kex: client: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
kex: client: none
kex: client: none
kex: client: 
kex: client: 
kex: algorithm: ecdh-sha2-nistp256
kex: host key algorithm: ssh-rsa
kex: server->client cipher: aes128-ctr MAC: hmac-sha2-256 compression: none
kex: client->server cipher: aes128-ctr MAC: hmac-sha2-256 compression: none
SSH_MSG_KEX_ECDH_INIT sent
expecting SSH_MSG_KEX_ECDH_REPLY
ssh_rsa_verify: ssh-rsa signature true
Permanently added '....' (RSA) to the list of known hosts.
SSH_MSG_NEWKEYS sent
SSH_MSG_NEWKEYS received
SSH_MSG_SERVICE_REQUEST sent
SSH_MSG_SERVICE_ACCEPT received
Authentications that can continue: publickey,password
Next authentication method: publickey
PubkeyAcceptedAlgorithms = ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss
Signature algorithms unavailable for non-agent identities = [ssh-ed25519, ssh-ed448]
No server-sig-algs found, using PubkeyAcceptedAlgorithms = [ssh-ed25519, ecdsa-sha2-nistp256, ecdsa-sha2-nistp384, ecdsa-sha2-nistp521, rsa-sha2-512, rsa-sha2-256, ssh-rsa, ssh-dss]
rsa-sha2-512 preauth success
rsa-sha2-512 auth failure
rsa-sha2-256 preauth success
rsa-sha2-256 auth failure
ssh-rsa preauth success
ssh-rsa auth success
Authentication succeeded (publickey).

**Comment by norrisjeremy** [comment]
Hi @ivanpedruzzi,

Great, thanks for confirming!

Thanks,
Jeremy
