### ISSUE TITLE
Add gh-pages with Javadoc

### ISSUE THREAD

**Issue by robtimus** [mwiede/jsch#273]
Right now I'm using https://epaul.github.io/jsch-documentation/javadoc/ to link to, but that's obviously not the same as this new version. It would be nice if you could add a simple site including Javadoc.

You can even use a GitHub action to do that, using https://github.com/JamesIves/github-pages-deploy-action. For instance, I've setup a trigger so each release tag automatically leads to an update of the site for most of my projects.

**Comment by mwiede** [comment]
I have set the javadoc up at gh pages now https://mwiede.github.io/jsch/
it hopefully suits your needs.
Best,Matthias

**Comment by robtimus** [comment]
I see that you use Java 17 to build it. While that does provide a nice UI, it means it cannot be used to link to when building using Java 8. The other way around, Javadoc built with Java 8 can used be used to link to when building using Java 9 or up. Is it therefore possible for you to use Java 8 to build the Javadoc instead of Java 17?

**Comment by norrisjeremy** [comment]
I'm not sure I understand why it matters what version of Java the Javadocs are built with?

**Comment by norrisjeremy** [comment]
Also, have you considered simply browsing them via [javadoc.io](https://javadoc.io/doc/com.github.mwiede/jsch/latest/com.jcraft.jsch/module-summary.html)?

**Comment by robtimus** [comment]
If I link to modular Javadoc pages from a non-modular project, none of the links to those Javadoc pages are properly resolved. Instead, they show up as the fully qualified class name without a link. I hadn't thought of javadoc.io, but that also builds modular Javadocs, making them useless for Java 8 projects. I am still maintaining some of those because some of my target audience cannot upgrade to Java 11 yet.

**Comment by norrisjeremy** [comment]
If you're referring to having Javadocs from your own project link properly to upstream Javadocs that are built with Java 10+, I'd recommend something like this: https://stackoverflow.com/a/49482502.

You can add something like this in the `maven-javadoc-plugin` configuration of your project:
```
<offlineLinks>
    <offlineLink>
        <url>https://javadoc.io/doc/com.github.mwiede/jsch/0.2.7/</url>
        <location>${project.basedir}/src/main/resources/com.github.mwiede/jsch</location>
    </offlineLink>
</offlineLinks>
```

Then in the `src/main/resources/com.github.mwiede/jsch` directory, create a file named `package-list` that contains the line:
```
com.jcraft.jsch
```

I've done this in other projects that build Javadocs with Java 8 and need to link to other project's Javadocs that are built with Java 10+.

**Comment by robtimus** [comment]
I had to add the module name to the URL (https://javadoc.io/doc/com.github.mwiede/jsch/0.2.7/com.jcraft.jsch/), but that works like a charm. Thanks!
