### ISSUE TITLE
com.jcraft.jsch.JSchException: Auth fail for methods 'publickey,gssapi-keyex,gssapi-with-mic,password'

### ISSUE THREAD

**Issue by 1912158597-george** [mwiede/jsch#277]
com.jcraft.jsch.JSchException: Auth fail for methods 'publickey,gssapi-keyex,gssapi-with-mic,password'

**Comment by mwiede** [comment]
which version of Jsch are you using?

I recommend searching on stackoverflow.

Otherwise we need output of Jsch Logger to see what is going wrong.

**Comment by 1912158597-george** [comment]
<dependency>
            <groupId>com.github.mwiede</groupId>
            <artifactId>jsch</artifactId>
            <version>0.2.7</version>
        </dependency>

Can OpenSSH Be Upgraded to Solve the Problem?
