### ISSUE TITLE
2FA SFTP servers

### ISSUE THREAD

**Issue by Nogsmoke** [mwiede/jsch#292]
We've run into an SFTP server with two factor authentication that requires both public key and password authentication to log in.  Can this be supported?  Both auth methods are supported, and the auth elements are configured on the session.

Thanks!

   [script] 2023-03-21 08:02:01,862 INFO  com.jcraft.jsch -- SSH_MSG_NEWKEYS sent
   [script] 2023-03-21 08:02:01,882 INFO  com.jcraft.jsch -- SSH_MSG_NEWKEYS received
   [script] 2023-03-21 08:02:01,891 INFO  com.jcraft.jsch -- SSH_MSG_SERVICE_REQUEST sent
   [script] 2023-03-21 08:02:01,974 INFO  com.jcraft.jsch -- SSH_MSG_SERVICE_ACCEPT received
   [script] 2023-03-21 08:02:02,060 INFO  com.jcraft.jsch -- Authentications that can continue: publickey,password
   [script] 2023-03-21 08:02:02,063 INFO  com.jcraft.jsch -- Next authentication method: publickey
   [script] 2023-03-21 08:02:03,468 INFO  com.jcraft.jsch -- Authentications that can continue: password
   [script] 2023-03-21 08:02:03,470 INFO  com.jcraft.jsch -- Next authentication method: password
   [script] 2023-03-21 08:02:03,556 INFO  com.jcraft.jsch -- Disconnecting from {server removed}
   [script] 2023-03-21 08:02:03,563 WARN  PARTNERCHECK -- Error during checkPartner: JavaException: com.jcraft.jsch.JSchException: Auth fail for methods 'publickey,password'

**Comment by mwiede** [comment]
Have you seen https://stackoverflow.com/a/39511487/2290153 ?

**Comment by Nogsmoke** [comment]
I had not, I'll have to see if that's workable in our environment.  Thanks!
