### ISSUE TITLE
Algorithm negotiation fail after upgrading Server side Tectia client 6.5.1

### ISSUE THREAD

**Issue by kvbdev1985** [mwiede/jsch#307]
I have tried connecting to destination server after upgrading destination server with Tectia client to 6.5.1  `Algorithm negotiation failure`, attached the detailed log file

[FTP-jsch-0.1.55.log](https://github.com/mwiede/jsch/files/11205809/FTP-jsch-0.1.55.log)

**Comment by norrisjeremy** [comment]
Hi @kvbdev1985,

You will need to upgrade from the old JSch 0.1.55 release to the latest release from this fork (0.2.8) in order to connect to this Tectia 6.5.1 server.

Thanks,
Jeremy

**Comment by norrisjeremy** [comment]
Hi @kvbdev1985,

The old JSch 0.1.55 release doesn't support crypto algorithms that your Tectia 6.5.1 server requires:

KEX algorithms:
```
INFO: kex: server: diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,curve25519-sha256,diffie-hellman-group14-sha256@ssh.com,curve25519-sha256@libssh.org,ext-info-s
INFO: kex. client: ecdh-sha2-nistp256, ecdh-sha2-nistp384, ecdh-sha2-nistp521, diffie-hellman-group14-shal, diffie-hellman-group-exchange-sha256, diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1
```

Server Key algorithms:
```
INFO: kex: server: rsa-sha2-256,rsa-sha2-512,ssh-rsa-sha256@ssh.com
INFO: kex: client: ssh-rsa,ssh-dss,ecdsa-sha2-nistp256,ecdsa-shal-nistp384,ecdsa-sha2-nistp521
```

MAC algorithms:
```
INFO: kex: server: hmac-sha2-512,hmac-sha2-256,hmac-sha512@ssh.com,hmac-sha384@ssh.com
INFO: kex: client: hmac-md5,hmac-shal,hmac-sha2-256,hmac-shal-96,hmac-md5-96
```

Thanks,
Jeremy

**Comment by kvbdev1985** [comment]
Thanks Jeremy,

I agree what you are saying, so basically latest crypto are not supported by JSch 0.1.55 release, 
I do see there is lot of dependency on this Jsch lib, why can't jCraft is supporting it?

On a quick note I can able to connect able to FTP from source server to destination server by running a simple sftp cmd on top of the server, 
will this crypto algorithms won't be an issue on server side sftp?

Thanks,
