### ISSUE TITLE
jsch-0.2.7: SFTP session connection fails due to "End of IO stream read"

### ISSUE THREAD

**Issue by alex-rentz** [mwiede/jsch#339]
Java version: 11
JSCH Version: jsch-0.2.7

I am seeing the following error when trying to connect to SFTP. It looks like the session gets created, but after the KEXINIT is sent, we aren't able to receive the corresponding KEXINIT message due to an IO error.

```
java.io.IOException: End of IO Stream Read
    at com.jcraft.jsch.IO.getByte(IO.java:85)
    at com.jcraft.jsch.Session.read(Session.java:1177)
    at com.jcraft.jsch.Session.connect(Session.java:319)
    ... <proprietary code from here on out>
```

Inspecting the code, it looks like this could be due to reading too many bytes from the stream, perhaps? 

Here are the log lines immediately preceding the error:

```
Connecting to <secret> port 22
Connection established
Remote version string: SSH-2.0-2.0
Local version string: SSH-2.0-JSCH_0.2.7
CheckCiphers: chacha20-poly1305@openssh.com
CheckKexes: curve25519-sha256,curve25519-sha256@libssh.org,curve448-sha512
CheckSignatures: ssh-ed25519,ssh-ed448
server_host_key proposal before known_host reordering is: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256
server_host_key proposal after known_host reordering is: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256
SSH_MSG_KEXINIT sent
```

I don't know whether this is an issue on my end or an issue within the code. Any assistance is appreciated.

**Comment by norrisjeremy** [comment]
Hi @alex-rentz,

This is almost certainly some sort of network issue, in which the TCP connection is being prematurely closed.
See https://github.com/mwiede/jsch/issues/94#issuecomment-965072561.

Thanks,
Jeremy

**Comment by alex-rentz** [comment]
Hi @norrisjeremy , thanks for the suggestion. We can try and troubleshoot firewall settings and such.

Since the cipher being read is chacha20 per the logs, should we even be entering the code block where it is currently throwing the exception? It looks like it would be going a different way. What do you think?

**Comment by alex-rentz** [comment]
Never mind, restarting the customer's SFTP server has revealed it to be an "Algorithm negotiation fail" error message. Thanks again.

**Comment by norrisjeremy** [comment]
> 

FYI, the `CheckCiphers: chacha20-poly1305@openssh.com` log message doesn't mean that is the negotiated cipher that is being used.
But rather it means it is a cipher suite that JSch dynamically tests and makes sure the Java implementation is usable or not (since it requires Bouncy Castle): if JSch finds that it is unusable because Bouncy Castle is missing, then it will remove it from the ciphers that are advertised as available to the SSH server so that the SSH connection does not attempt to utilize it.

**Comment by alex-rentz** [comment]
Closing out since it is a config issue and not a code issue.
