### ISSUE TITLE
NullPointerException at connect

### ISSUE THREAD

**Issue by uffeweil** [mwiede/jsch#34]
Hi!

First I'd like to thank you for proving this new distribution of Jsch. Very appreciated!! 

Using a key (New openssh-v1-private-key format) that has not been added at the server leads to NullPointerException.
Converting the key to PEM format and the error is instead the expected "Auth fail".

`Caused by: java.lang.NullPointerException
	at com.jcraft.jsch.KeyPairDeferred.getKeyTypeName(KeyPairDeferred.java:120)
	at com.jcraft.jsch.IdentityFile.getAlgName(IdentityFile.java:106)`

Full log and key in attached files below.
By the way in the release notes you state that ssh-ed25519 is supported. Is this implementation ripped out of Java 15 or does it require a Java 15 VM to be used?

Kind regards Ulf

[FailDbvisNewSSHKey.txt](https://github.com/mwiede/jsch/files/6041123/FailDbvisNewSSHKey.txt)
[id_rsa_notTrustedNewSSHFormat.txt](https://github.com/mwiede/jsch/files/6041148/id_rsa_notTrustedNewSSHFormat.txt)

**Comment by mwiede** [comment]
Hi Ulf, thanks for reporting this issue, need to look into that.

Regarding the ssh.ed25519 question, yes you need to use Java 15, compare to https://github.com/subhra74/snowflake/issues/16#issuecomment-779862697

**Comment by uffeweil** [comment]
Great, thanks for the quick answer!

**Comment by mwiede** [comment]
note to myself: the NPE occurs, when an encrypted openssh v1 key as added as identity without setting its password.
in this situation we should throw an error in all methods, telling that the key has not been decrypted yet.

**Comment by uffeweil** [comment]
Hi Matthias,

Just uploaded a trace which indicates the same error for a key that has been added. The user runs Java 15.
I don't know if this helps 

[traceKnownKeyJava15.txt](https://github.com/mwiede/jsch/files/6081628/traceKnownKeyJava15.txt)

Regards
Ulf

**Comment by mwiede** [comment]
Hi Ulf,
what do you mean by "key has been added"?
I looked at the code, and the only situation, in which the NPE can occur, is when an encrypted key as added as identity without a password. You example key from id_rsa_notTrustedNewSSHFormat.txt contains an enycrypted key with cipher aes256-ctr.
So I guess you added the key as` jSch.addIdentity(prvkey)` instead of `jSch.addIdentity(prvkey, password);`
Best regards
Matthias

**Comment by uffeweil** [comment]
Hi Matthias,

Sorry for being unclear by added I mean it added as a trusted key at the server.

Implementation wise we are doing something like:
 
 ```
jsch.addIdentity(sshPrivateKeyFile); 
 final Session sshSession = jsch.getSession(sshUserid, sshHost, sshPort);
 UserInfo ui = new MyUserInfo(sshPassword, sshPassphrase, dialogOwner);
 sshSession.setUserInfo(ui);
```
 
 This is the same implementation not matter of key formats. No problem of connecting using other keys in our product (DbVisualizer)
 Our customer uses the same key successfully using SSH in a terminal which is of course not utilizing Jsch.

**Comment by mwiede** [comment]
ok, thanks for your clarification. I think I came closer to the problem. The issue comes, when the key is encrypted and the identity is added without the passphrase. Instead the passphrase is coming from Userinfo#getPassphrase() and the decryption happens in com.jcraft.jsch.UserAuthPublicKey line 204. For KeypairDeferred this is too late, as the getAlgName() is needed in line 92.
I suggest that we are moving the while loop with the decryption up to line 91

**Comment by uffeweil** [comment]
Hi Matthias
Thanks for all your help. From the Pull request  I guess you you are already on this!
Regards Ulf

**Comment by mwiede** [comment]
Hi Ulf, I released the library in version 0.1.62. Please check whether the issue is fixed.

**Comment by uffeweil** [comment]
Hi Matthias,
That was really quick!! I will ask our customer if he could test. 
Many thanks for the quick turnaround!!
Regards
Ulf

**Comment by uffeweil** [comment]
Hi Mattias,

Is there a Jar somewhere? Or am I being to impatient? :-)

Regards 
Ulf

**Comment by mwiede** [comment]
Yes maven Central sync can take up to 24 hours 😁

uffeweil <notifications@github.com> schrieb am Do., 4. März 2021, 17:36:

**Comment by uffeweil** [comment]
Hi Mattias

Just thought I would inform you that our user has reported that he can now connect using the 0.1.62 version.
Many thanks for a great fix and quick turnaround. Awsome!

Regards 
Ulf
