### ISSUE TITLE
Consider adding jar binaries to release snapshot workflow

### ISSUE THREAD

**Issue by citizenTwice** [mwiede/jsch#372]
Enhancement. Improve lead-times & ease of deployment.

**Comment by norrisjeremy** [comment]
Hi @citizenTwice,

I'm not sure I understand what you are asking for: can you elaborate?

Thanks,
Jeremy

**Comment by norrisjeremy** [comment]
Hi @citizenTwice,

This fork is distributed via [Maven Central](https://central.sonatype.com/artifact/com.github.mwiede/jsch/).

Thanks,
Jeremy

**Comment by citizenTwice** [comment]
@norrisjeremy Got it, exactly what I was looking for.  Thank you!
