### ISSUE TITLE
Illegal charater '&' in password using JSCH to connect to sftp server

### ISSUE THREAD

**Issue by SteadyStill** [mwiede/jsch#376]
Hi,
I faced error when having '&' in password with JSCH. I tried to escape with '\&' but it did not work.
Can you please comment on this issue?

        <dependency>
            <groupId>com.github.mwiede</groupId>
            <artifactId>jsch</artifactId>
            <version>0.2.7</version>
        </dependency>

Thanks.

**Comment by norrisjeremy** [comment]
Hi @SteadyStill,

You will need to provide more details if you would like us to assist you.

1. Have you tested and confirmed the issue still happens with the latest JSch release (0.2.11)?
2. Are you receiving an exception? If so, can you provide the details of this exception?
3. What kind of server are you connecting to?
4. It may also help to enable logging in JSch and provide those logs.
5. Also if you can provide sample code illustrating the problem that can help as well.

Thanks,
Jeremy

**Comment by SteadyStill** [comment]
Hi @norrisjeremy 

Thanks for your help. sorry for the late answer. Just want to let you know this issue was caused by business code instead of the lib. It worked with <version>0.2.7</version>

Thanks,
Weihua
