### ISSUE TITLE
IPV6 support

### ISSUE THREAD

**Issue by liftoff-sr** [mwiede/jsch#38]
Does this library support talking to an SSH server running only IPV6?

If not, what would have to be done to support that?

**Comment by mwiede** [comment]
I am not aware that it should not work. Did you try it? What was the error message?

**Comment by liftoff-sr** [comment]
I just tried today for the first time and IPv6 works fine AFAICT.

**Comment by liftoff-sr** [comment]
No issue

**Comment by BigDataHunter** [comment]
IPV6 how to support
