### ISSUE TITLE
Question: support for umac-128-etm@openssh.com

### ISSUE THREAD

**Issue by avnerw74** [mwiede/jsch#39]
Hi,

Is the umac-128-etm@openssh.com MAC algorithm supported?
If not, are there plans for supporting it?

Thanks,
Avner

**Comment by norrisjeremy** [comment]
The `umac` algorithms aren't currently supported (`umac-64@openssh.com,umac-128@openssh.com,umac-64-etm@openssh.com,umac-128-etm@openssh.com`).

**Comment by avnerw74** [comment]
Thanks @norrisjeremy for the update!
