### ISSUE TITLE
channel.getInputStream() should warn if the channel has already connected

### ISSUE THREAD

**Issue by pshem** [mwiede/jsch#403]
We recently fixed a bug in our code where we were doing two things in the wrong order, which would lead to a race condition.

Examples, such as https://github.com/mwiede/jsch/blob/c6970b8edd90e185fde7d9023f683ff3b0345776/examples/ScpTo.java#L43-L45 show you should first grab an InputStream and then connect.

Our code had:
```java
channel.connect();
InputStream in = channel.getInputStream();
List<String> response = readStream(in);
```

It mostly worked, but would occasionally fail, mostly when testing connections between two fastest machines located nearby.

Would it be possible to log a warning when you `getInputStream()` but the channel has already connected, or is that a valid scenario in some circumstances?

**Comment by norrisjeremy** [comment]
Hi @pshem,

I've included a change to add some logger warnings when `getInputStream()` or `getExtInputStream()` are called after `connect()` as part of #431.

Thanks,
Jeremy

**Comment by pshem** [comment]
Thank you very much - my older self would have noticed (we'd spent a week looking over debug level messages from JSch to figure out what was wrong before reading the documentation :smiling_face_with_tear:  )
