### ISSUE TITLE
Execution failed for JetifyTransform

### ISSUE THREAD

**Issue by mwarning** [mwiede/jsch#41]
I tried to use the this jsch fork as a drop in replacement for the original library:

app/build.gradle
```
dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.github.mwiede:jsch:0.1.62'
    ...
}
```

gradle.properties
```
android.useAndroidX=true
android.enableJetifier=true
```

Android Studio now gives me:
```
Execution failed for task ':app:javaPreCompileFdroidDebug'.
> Could not resolve all files for configuration ':app:fdroidDebugCompileClasspath'.
   > Failed to transform artifact 'jsch.jar (com.github.mwiede:jsch:0.1.62)' to match attributes {artifactType=android-classes, org.gradle.usage=java-runtime-jars}
      > Execution failed for JetifyTransform: /home/mwarning/.gradle/caches/modules-2/files-2.1/com.github.mwiede/jsch/0.1.62/de4b21c9c2d40481ec19644c16c66fc7a44027c8/jsch-0.1.62.jar.
         > Failed to transform '/home/mwarning/.gradle/caches/modules-2/files-2.1/com.github.mwiede/jsch/0.1.62/de4b21c9c2d40481ec19644c16c66fc7a44027c8/jsch-0.1.62.jar' using Jetifier. Reason: null. (Run with --stacktrace for more details.)
```

I also tried jsch 0.1.58 and cleared the cache each time.

Any idea how to fix this?

**Comment by mwarning** [comment]
I tried to create a new dummy project and added only:

```
implementation 'com.github.mwiede:jsch:0.1.62'
```

This gives me:

```
Execution failed for task ':app:mergeDebugJavaResource'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform jsch-0.1.62.jar (com.github.mwiede:jsch:0.1.62) to match attributes {artifactType=android-java-res, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for JetifyTransform: /home/mwarning/.gradle/caches/modules-2/files-2.1/com.github.mwiede/jsch/0.1.62/de4b21c9c2d40481ec19644c16c66fc7a44027c8/jsch-0.1.62.jar.
         > Failed to transform '/home/mwarning/.gradle/caches/modules-2/files-2.1/com.github.mwiede/jsch/0.1.62/de4b21c9c2d40481ec19644c16c66fc7a44027c8/jsch-0.1.62.jar' using Jetifier. Reason: IllegalArgumentException, message: Unsupported class file major version 59. (Run with --stacktrace for more details.)
           Suggestions:
            - Check out existing issues at https://issuetracker.google.com/issues?q=componentid:460323&s=modified_time:desc, it's possible that this issue has already been filed there.
            - If this issue has not been filed, please report it at https://issuetracker.google.com/issues/new?component=460323 (run with --stacktrace and provide a stack trace if possible).
```

**Comment by mwarning** [comment]
`Unsupported class file major version 59` seem to be the key issue here.

**Comment by mwarning** [comment]
I tried with Android Studio 4.1.3 as well. No change.

**Comment by norrisjeremy** [comment]
JSch is a multi-release jar that contains some Java 15 classes (class file major version 59) for ssh-ed448 / ssh-ed25519 support.
I'm not familiar with Android development, but the messages you provided seem to indicate it doesn't cope with the optional Java 15 classes included with the jar. I'm not sure if there is a way to configure it to ignore the Java 15 classes in the jar (they are under `META-INF/versions/15/`).

**Comment by mwarning** [comment]
Thank your for the additional information!

Android Studio has on Java 8 (and 10) available. I don't know how to work around this. :/

**Comment by norrisjeremy** [comment]
FYI, there are also some optional Java 11 classes present (class file major version 55) also contained in the jar for curve25519-sha256 / curve448-sha512 & chacha20-poly1305 support; they are under `META-INF/versions/11/`.

**Comment by norrisjeremy** [comment]
As I mentioned, am I not at all familiar with Android development. But briefly reading online, it seems that this `JetifyTransform` build step is used to help transform some sort of Android specific support library references?
If so, perhaps it isn't needed for JSch, since it is a pure Java library that doesn't use Android specific support libraries?
Is it possible to configure your Gradle build to exclude running the `JetifyTransform` step on the JSch jar?

**Comment by norrisjeremy** [comment]
If I'm reading the link below correctly, it seems it's possible to exclude certain libraries in your gradle.properties?

https://stackoverflow.com/a/53869014

**Comment by mwarning** [comment]
This line my `app/build.gradle`:
```
implementation 'com.github.mwiede:jsch:0.1.62'
```

This works if I check "Use legacy android.support libraries." while creating a new Android Studio project. But this is only supported until Android 10 (Q).

If I do not use these support libraries, then I get this `Unsupported class file major version 59` error. :(

**Comment by mwarning** [comment]
@norrisjeremy

```
android.jetifier.blacklist = ...
```
Android Studio tells me that this option is not supported anymore.

**Comment by mwarning** [comment]
With a default android project (`Use legacy android.support libraries.` is disabled), compiling works until `com.github.mwiede:jsch:0.1.60`. With `0.1.61`, I get the `Unsupported class file major version 59` error.

**Comment by mwarning** [comment]
ssh-ed25519 support would be awesome. Would it be possible to integrate the code into jsch as a fallback mechanism?

**Comment by norrisjeremy** [comment]
I'm not sure what else to do if Android removed the ability to exclude running the JetifyTransform on specific libraries. You may need to inquire on some Android support forums to see if there is some other way to exclude the JSch jar from this step?

As for the ssh-ed25519 support: the code in JSch to support it relies upon [JEP 339](https://openjdk.java.net/jeps/339), which was added into Java 15. It's not feasible to extract all that code out of OpenJDK and integrate it directly into JSch.

**Comment by mwarning** [comment]
I got this line in `gradle.properties` working:
```
android.jetifier.blacklist=jsch
```
But, while the app now compiles using jsch 0.1.62 , I get exceptions like `java.lang.ClassNotFoundException: com.jcraft.jsch.jce.KeyPairGenEdDSA`.

Sorry, but I have to look for a different ssh lib for my use case. Thank a lot for the support.

**Comment by mwarning** [comment]
Wouldn't support for Bouncy Castle a possibility?

**Comment by jda258** [comment]
I was able to compile after upgrading to the latest version of Gradle available in Android Studio (7.0.2).

**Comment by norrisjeremy** [comment]
Hi @mwarning & @jda258,

So is everything working for you now with newer versions of Gradle & Android Studio?

Thanks,
Jeremy

**Comment by mwarning** [comment]
well, I have switched to a different library, since I was not able to resolve the issue  (org.connectbot:sshlib)

**Comment by jda258** [comment]
Hi @norrisjeremy,

It is working well for me. I have migrated to this fork for the Flutter plugin I manage: https://pub.dev/packages/ssh2

I'm also using it in production for an Android app. Thanks so much for your work on this fork!

Thanks,
Josh

**Comment by norrisjeremy** [comment]
@jda258,

This is excellent news to hear! I am glad it is working for you now.

Thanks,
Jeremy

**Comment by norrisjeremy** [comment]
> Wouldn't support for Bouncy Castle be a possibility for jsch?

Hi @mwarning,
FYI, in the new [0.1.66](https://github.com/mwiede/jsch/releases/tag/jsch-0.1.66) release we added Bouncy Castle implementations for various algorithms that were only supported in newer Java versions. So you should be able to make use of them now with older Java releases by simply adding the Bouncy Castle library to your application(s).

Thanks,
Jeremy

**Comment by mwarning** [comment]
@norrisjeremy thank you!

**Comment by mendhak** [comment]
FWIW, and for future searchers.  
I was running into "AlgorithmParameters EC implementation not found" with version 0.1.58.    
And trying to use 0.1.67 resulted in "Unsupported class file major version 59"  

I had to update the Android Gradle Plugin to 7.0.2

```
classpath 'com.android.tools.build:gradle:7.0.2'
```

And the Gradle tool to 7.0.2

```
distributionUrl=https\://services.gradle.org/distributions/gradle-7.0.2-bin.zip
```

And ensure that the project's JDK was set to at least version 11.
