### ISSUE TITLE
SFTP server fingerprint cannot be taken in MD5 format using HostKey.getFingerPrint()

### ISSUE THREAD

**Issue by anamikagsingh** [mwiede/jsch#430]
Hi,

In our application, we have used mwiede Jsch library. Earlier, we were using Jcraft Jsch library (version 1.55) where we were able to get the server fingerprint in MD5 format. Now, after replacing the Jsch library with mwiede Jsch library (version 0.2.8), we see that the fingerprint is taken in SHA256 hash value. Please have a look at the method getFingerPrint() available under HostKey.java

In Jcraft Jsch library (version 1.55):

public String getFingerPrint(JSch jsch){
    HASH hash=null;
    try{
      Class c=Class.forName(jsch.getConfig("md5"));
      hash=(HASH)(c.newInstance());
    }
    catch(Exception e){ System.err.println("getFingerPrint: "+e); }
    return Util.getFingerPrint(hash, key);
  }

In mwiede Jsch library (version 0.2.8):

public String getFingerPrint(JSch jsch) {
    HASH hash = null;
    try {
      String _c = JSch.getConfig("FingerprintHash").toLowerCase();
      Class<? extends HASH> c = Class.forName(JSch.getConfig(_c)).asSubclass(HASH.class);
      hash = c.getDeclaredConstructor().newInstance();
    } catch (Exception e) {
      if (jsch.getInstanceLogger().isEnabled(Logger.ERROR)) {
        jsch.getInstanceLogger().log(Logger.ERROR, "getFingerPrint: " + e.getMessage(), e);
      }
    }
    return Util.getFingerPrint(hash, key, false, true);
  }

When I try to get the server fingerprint using getFingerPrint() method, the Server fingerprint for the same SFTP server is generated in below format:

When Jcraft Jsch library (version 1.55) is used:                   
Server Fingerprint: b0:67:bb:26:aa:65:0f:32:a1:0d:35:ae:26:85:a2:98     (128-bit (16-byte) hash value) 
When mwiede Jsch library (version 0.2.8) is used:                  
Server Fingerprint: 88:7a:ce:65:b4:a1:3f:c5:f6:38:ce:a5:70:32:ee:38:b6:9d:50:4f:ae:01:0d:ed:e7:26:52:b3:b6:81:10:1f      (256-bit (32-byte) hash value)

Is it possible to get the fingerprint in MD5 format again? Or is it possible to make it switchable so that MD5 fingerprint )i.e., 128-bit (16-byte) hash value) can also be fetched using getFingerPrint() method? Thanks a lot!

Regards,
Anamika

**Comment by norrisjeremy** [comment]
Hi @anamikagsingh,

I believe you should be able to have MD5 type fingerprints by using `session.setConfig("FingerprintHash", "MD5");` or `JSch.setConfig("FingerprintHash", "MD5");`.

Thanks,
Jeremy

**Comment by anamikagsingh** [comment]
Hi Jeremy,

Thanks for your suggestion. The first option (i.e., using session.setConfig("FingerprintHash", "MD5")), I tried before as well but it did not change the fingerprint format.  So, I tried the other option now that is setting the format using JSch.setConfig(), and the format is changed from 32-byte hash to 16-byte hash. But looks like it is changing the sha-256 fingerprint to 16-byte hash value now.

Server Fingerprint without setting MD5: 88:7a:ce:65:b4:a1:3f:c5:f6:38:ce:a5:70:32:ee:38:b6:9d:50:4f:ae:01:0d:ed:e7:26:52:b3:b6:81:10:1f   
is now changed to 
83:2e:a6:14:1c:77:63:3d:1c:ee:00:75:8c:77:d1:95

When I use old Jsch library, the server fingerprint is as follows: b0:67:bb:26:aa:65:0f:32:a1:0d:35:ae:26:85:a2:98

Regards,
Anamika

**Comment by norrisjeremy** [comment]
Hi @anamikagsingh,

I am unable to reproduce the behavior you are seeing using the integration test we have:
```
mvn failsafe:integration-test -DskipITs=false -Dit.test=AlgorithmsIT#testFingerprintHashes -Dmaven.test.dependency.excludes=org.bouncycastle:bcprov-jdk18on
```

Can you provide a code example that produces the behavior you are seeing?

Thanks,
Jeremy

**Comment by norrisjeremy** [comment]
Hi @anamikagsingh,

In reviewing this further, I'm guessing that you are extracting a host key fingerprint via the `HostKey.getFingerprint()` method?

Assuming that is true, then the only way to change it back to MD5 would be by using `JSch.setConfig("FingerprintHash", "MD5")` , since the `HostKey` object is not associated to a `Session` object, and thus it can only use the `JSch` global config.

As for why the server's MD5 fingerprint differs when using the old JSch library versus this fork, I believe this is likely because the HostKey from your server is different because the older JSch library is negotiating a different server key algorithm than this fork.

I would suggest adding a call to `HostKey.getType()` and confirm whether or not the type is the same for the old version of JSch versus this fork.

Thanks,
Jeremy

**Comment by anamikagsingh** [comment]
Hi Jeremy,

Yes, I am using the method HostKey.getFingerprint() to get the fingerprint. You can use the below code (by just providing the values for your SFTP server) to check/reproduce the behavior. 

`import com.jcraft.jsch.*;

public class SFTPServerFingerprint {
    public static void main(String[] args) {
        String host = "sftp server";
        int port = 22; // SFTP default port
        String user = "sftpServerUser";
        String password = "sftpServerPassword"; 

        JSch jsch = new JSch();
        Session session = null;

       try {
            session = jsch.getSession(user, host, port);
            session.setPassword(password);

            // Connect to the SFTP server
            session.setConfig("StrictHostKeyChecking", "no"); // Disable host key checking
            //JSch.setConfig("FingerprintHash", "MD5");
            //JSch.setConfig("FingerprintHash", "SHA256");
            //JSch.setConfig("FingerprintHash", "SHA1");
            session.connect();

            // get and print server's Fingerprint and keytype
           String fingerprint = session.getHostKey().getFingerPrint(jsch);
           String keyType = session.getHostKey().getType();
           System.out.println("Server Fingerprint: " + fingerprint);
           System.out.println("Server Keytype: " + keyType);

        } catch (JSchException e) {
            e.printStackTrace();
        } finally {
            if (session != null && session.isConnected()) {
                session.disconnect();
            }
        }
    }
}
`
By default, it prints SHA256 fingerprint hash. If you uncomment 'MD5' option, different format can be fetched.  Here, I have used jsch-0.2.8.jar. 

The keyType for my/same SFTP server:
                    When jsch-0.2.8 library is used:  ecdsa-sha2-nistp256.
                    When old Jsch library is used :   ssh-rsa

Regards,
Anamika

**Comment by anamikagsingh** [comment]
Hi Jeremy,

Yes, I am using the method HostKey.getFingerprint() to get the fingerprint. You can use the below code (by just providing the values for your SFTP server) to check/reproduce the behavior.

`
import com.jcraft.jsch.*;
public class SFTPServerFingerprint {
public static void main(String[] args) {
String host = "sftp server";
int port = 22; // SFTP default port
String user = "sftpServerUser";
String password = "sftpServerPassword";

    JSch jsch = new JSch();
    Session session = null;

   try {
        session = jsch.getSession(user, host, port);
        session.setPassword(password);

        // Connect to the SFTP server
        session.setConfig("StrictHostKeyChecking", "no"); // Disable host key checking
        //JSch.setConfig("FingerprintHash", "MD5");
        //JSch.setConfig("FingerprintHash", "SHA256");
        //JSch.setConfig("FingerprintHash", "SHA1");
        session.connect();

        // get and print server's Fingerprint and keytype
       String fingerprint = session.getHostKey().getFingerPrint(jsch);
       String keyType = session.getHostKey().getType();
       System.out.println("Server Fingerprint: " + fingerprint);
       System.out.println("Server Keytype: " + keyType);

    } catch (JSchException e) {
        e.printStackTrace();
    } finally {
        if (session != null && session.isConnected()) {
            session.disconnect();
        }
    }
}
}
`

By default, it prints SHA256 fingerprint hash. If you uncomment 'MD5' option, different format can be fetched. Here, I have used jsch-0.2.8.jar.

The keyType for my/same SFTP server:
When jsch-0.2.8 library is used: ecdsa-sha2-nistp256.
When old Jsch library is used : ssh-rsa

Regards,
Anamika

**Comment by norrisjeremy** [comment]
Hi @anamikagsingh,

I'm not sure what the problem is then?

1. To have `HostKey.getFingerPrint()` return the MD5 fingerprint, you will need to instruct JSch to utilize the MD5 algorithm, via `JSch.setConfig("FingerprintHash", "MD5")`.
2. To have JSch negotiate using an `ssh-rsa` host key instead of `ecdsa-sha2-nistp256`, you would need to either add the `ssh-rsa` signature algorithm (if your server requires the use of RSA/SHA1 signatures), or adjust the priority of the `rsa-sha2-256` and/or `rsa-sha2-512` algorithms (if your server can support RSA/SHA2 signatures) to be ahead of other algorithms like `ecdsa-sha2-nistp256 `, by changing the `HostKeyAlgorithms` setting, via either `session.setConfig("HostKeyAlgorithms", "...")` or `JSch.setConfig("HostKeyAlgorithms", "...")`.

Thanks,
Jeremy

**Comment by anamikagsingh** [comment]
Hi Jeremy,
Thanks for the suggestion. When I give priority to ssh-rsa keytype over ecdsa, it gives me expected result.

Regards,
Anamika
