### ISSUE TITLE
Question about .jar file

### ISSUE THREAD

**Issue by BrunoDurren** [mwiede/jsch#442]
Hello,
I used Jsch lib for years now but unfortunately the remote server has been upgraded and my transfer is now broken.
I have integrated the Jsch lib into a oracle plsql environnement with the jar file of Jsch. Since I'm not (at all) a java developper, could you provide a jar file ? thanx in advance

**Comment by norrisjeremy** [comment]
Hi @BrunoDurren,

JSch is published to [Maven Central](https://repo1.maven.org/maven2/com/github/mwiede/jsch/)

Thanks,
Jeremy

**Comment by BrunoDurren** [comment]
Wow, Thank you. I will test it asap

**Comment by BrunoDurren** [comment]
I'am a bit forward, but stucked: The server refuses my proposal and respond: 
serverProposal="chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com"

is there a cypher method that is natively supported in theese proposal ?

**Comment by norrisjeremy** [comment]
Hi @BrunoDurren,

Other than `chacha20-poly1305@openssh.com` (which requires [Bouncy Castle](https://www.bouncycastle.org/java.html)) all the ciphers you listed above work with JSch natively without any other libraries.

Thanks,
Jeremy

**Comment by BrunoDurren** [comment]
I do this:
            session.setConfig("cipher.s2c", "aes128-ctr");
            session.setConfig("cipher.c2s", "aes128-ctr");

Is this not correct ?

**Comment by norrisjeremy** [comment]
Hi @BrunoDurren,

That should be fine. It's very likely that is failing for another reason, but since you have not provided a full copy of logs from a failed connection nor a full example of code you are using, it is difficult for us to tell you why.

Thanks,
Jeremy
