### ISSUE TITLE
How to figure the server-side ciphers?

### ISSUE THREAD

**Issue by nskmda** [mwiede/jsch#471]
Team,

A general question: is there any way to log which ciphers are used on the server side?
E.g., to configure the lib to have logger print this information for later analysis?

Thanks.

**Comment by norrisjeremy** [comment]
Hi @nskmda,

You can configure a logger using `JSch.setLogger(...)`.
We have several built-in loggers you can use:
- `com.jcraft.jsch.JplLogger`
- `com.jcraft.jsch.JulLogger`
- `com.jcraft.jsch.Log4j2Logger`
- `com.jcraft.jsch.Slf4jLogger`

You can also create your own by implementing the `com.jcraft.jsch.Logger` interface.

Thanks,
Jeremy

**Comment by nskmda** [comment]
Do you mean the server host cipher information is available to the logger?

**Comment by norrisjeremy** [comment]
Hi @nskmda,

Yes. JSch logs both the server and client proposals for all algorithms, as well as the algorithms that are ultimately negotiated, all at the INFO level:

```
server proposal: KEX algorithms: ...
server proposal: host key algorithms: ...
server proposal: ciphers c2s: ...
server proposal: ciphers s2c: ...
server proposal: MACs c2s: ...
server proposal: MACs s2c: ...
server proposal: compression c2s: ...
server proposal: compression s2c: ...
server proposal: languages c2s: ...
server proposal: languages s2c: ...
...
client proposal: KEX algorithms: ...
client proposal: host key algorithms: ...
client proposal: ciphers c2s: ...
client proposal: ciphers s2c: ...
client proposal: MACs c2s: ...
client proposal: MACs s2c: ...
client proposal: compression c2s: ...
client proposal: compression s2c: ...
client proposal: languages c2s: ...
client proposal: languages s2c: ...
...
kex: algorithm: ...
kex: host key algorithm: ...
kex: server->client cipher: ... MAC: ... compression: ...
kex: client->server cipher: ... MAC: ... compression: ...
```

Thanks,
Jeremy

**Comment by nskmda** [comment]
Wow! Thanks! Exactly what I needed.
