### ISSUE TITLE
Question about ssh-rsa deprecation

### ISSUE THREAD

**Issue by austinarbor** [mwiede/jsch#475]
Hello,
So I know you have answered tons of questions and have the FAQ entry about the openssh ssh-rsa deprecation and the steps we need to take to re-enable it for our clients. However, I am trying to write a test that "proves" my client works with ssh-rsa truly disabled. 

If I modify [sshd_config](https://github.com/mwiede/jsch/blob/master/src/test/resources/docker/sshd_config) from your tests and explicitly remove `ssh-rsa` from PubkeyAcceptedKeyTypes (and/or HostKeyAlgorithms) all of the [rsa tests](https://github.com/mwiede/jsch/blob/master/src/test/java/com/jcraft/jsch/AlgorithmsIT.java#L254-L262) start to fail. I've tried removing `ssh-rsa` from `sshd_config` on Ubuntu and Alpine images, but that always makes the rsa-sha2-256 & rsa-rsa2-512 algorithms fail as well.

Also, if I spin up a docker container with alpine:latest or ubuntu:latest, it seems like the ssh-rsa signature is always still enabled. My understanding of how this all works is probably the culprit, but do you know how I can prove Jsch still works with ssh-rsa disabled?

```
❯ docker run -it --rm alpine:latest sh -c 'apk update && apk add openssh && ssh -Q sig'
<truncated>
OK: 15 MiB in 25 packages
ssh-ed25519
sk-ssh-ed25519@openssh.com
ecdsa-sha2-nistp256
ecdsa-sha2-nistp384
ecdsa-sha2-nistp521
sk-ecdsa-sha2-nistp256@openssh.com
webauthn-sk-ecdsa-sha2-nistp256@openssh.com
ssh-dss
ssh-rsa
rsa-sha2-256
rsa-sha2-512
```

```
❯ docker run -it --rm ubuntu:latest sh -c 'apt-get update && apt-get install -y openssh-server && ssh -Q sig'
<truncated>
done.
ssh-ed25519
sk-ssh-ed25519@openssh.com
ssh-rsa
rsa-sha2-256
rsa-sha2-512
ssh-dss
ecdsa-sha2-nistp256
ecdsa-sha2-nistp384
ecdsa-sha2-nistp521
sk-ecdsa-sha2-nistp256@openssh.com
webauthn-sk-ecdsa-sha2-nistp256@openssh.com
```

**Comment by norrisjeremy** [comment]
Hi @austinarbor,

The `ssh -Q sig` command is not meant to indicate what signature algorithms are currently enabled by the `sshd_config` or `ssh_config`, but rather is intended to simply indicate all the possible algorithms that `ssh` could possibly support, if adequately configured.

Thanks,
Jeremy

**Comment by austinarbor** [comment]
@norrisjeremy thanks for your response! do you know why removing `ssh-rsa` from the sshd_config also makes the `rsa-sha2-256` and `rsa-sha2-512` tests fail?

**Comment by austinarbor** [comment]
Can confirm if I replace alpine 3.7 with 3.19 (latest), the rsa 256/512 algorithms work with ssh-rsa removed from the config. thank you!

**Comment by severach** [comment]
No need for guesswork. [Audit](https://www.sshaudit.com/) the SSH client and server and compare the lists.
