### ISSUE TITLE
Ordering of "ls"-method possible?

### ISSUE THREAD

**Issue by Bukama** [mwiede/jsch#483]
Hey everyone,
I'm not a linux or SSH expert so please apologis my question:

Is it technically possible to get file information (and dirs, etc.) the [`ls`](https://github.com/mwiede/jsch/blob/master/src/main/java/com/jcraft/jsch/ChannelSftp.java#L1547) in an ordered way, e.g. by file name or creation date?

As of now it seems the order of the entries you get is random.

I know that I could take the full list and order it in my own Java source code, but my question's background is regarded to FIFO logic. 

We only read a limited number of entries with a custom selector (might also be an interesting feature for the lib)

```
      LsEntrySelector selector = new LsEntrySelector() {
        public int select(LsEntry entry) {
          if (counter.get() < max) {
            lsEntriesVector.addElement(entry);
            counter.incrementAndGet();
            return CONTINUE;
          } else {
            return BREAK;
          }

        }
      };
```

As of now this gets us the first `max` files in the remote directory. We were asking ourself if we could ensure to get the first `max` oldest files (our files all have timestamp at the beginning, so file name would fit in our situation too) without having to transfer a full list of (in some situations) ten thousands files to then sort them and pick `max` out of them.

**Comment by norrisjeremy** [comment]
Hi @Bukama,

I don't believe there is a way to do this, as the `ls()` method is implemented via the `SSH_FXP_OPENDIR` & `SSH_FXP_READDIR` protocol messages, which do not support allowing the client to specify any sort of ordering or behavior to the server.

Thanks,
Jeremy

**Comment by Bukama** [comment]
Hey Jermey,
thank your for your response - I already thought that, because otherwise you would most probably already have implemented it :) 

Therefore I'll close this issue.

Thanks for all your work!
Matthias
