### ISSUE TITLE
Support for rsa2048-sha256 Key exchange

### ISSUE THREAD

**Issue by ShashikanthRaoT** [mwiede/jsch#493]
Hello,

This is not an issue but rather a query. I am trying to confirm if the library supports rsa2048-sha256 algorithm for key exchange. Can you please let me know.

Thank you

**Comment by mwiede** [comment]
I guess you mean `rsa-sha2-256` which is supported while 2048 is the RSA key size, which is the default

**Comment by ShashikanthRaoT** [comment]
Yes, Thank you for clarifying.

**Comment by norrisjeremy** [comment]
Hi @ShashikanthRaoT,

If you mean the `rsa2048-sha256` KEX algorithm as specified in [RFC-4432](https://datatracker.ietf.org/doc/html/rfc4432), then JSch does not currently have support for it.

Thanks,
Jeremy

**Comment by ShashikanthRaoT** [comment]
@norrisjeremy Thank you.

**Comment by ShashikanthRaoT** [comment]
@norrisjeremy - Are there any plans to support rsa2048-sha256 KEX algorithm ? Thank you.
