### ISSUE TITLE
Multi-Release jar for Java8

### ISSUE THREAD

**Issue by TunyaDrug** [mwiede/jsch#508]
I compile jar file of version 0.2.16. But when I'm import lib in my project (IntelliJ IDEA with Java 8) and try build project, IDE send me error:
> java: cannot access com.jcraft.jsch.JSchException
>   bad class file: [My proj path]/src/libs/jsch.jar!/com/jcraft/jsch/JSchException.class
>     class file has wrong version 60.0, should be 52.0
>     Please remove or make sure it appears in the correct subdirectory of the classpath

It feels like IDE is trying to use class for a higher version of Java
How to compile the library correctly so that it works with Java 8?

**Comment by norrisjeremy** [comment]
Hi @TunyaDrug,

I'm not sure that is something we can really help you with.
We would encourage you to simply use the official artifacts that we publish on [Maven Central](https://central.sonatype.com/artifact/com.github.mwiede/jsch) instead of trying to build your own.

Thanks,
Jeremy

**Comment by TunyaDrug** [comment]
Thanks, @norrisjeremy! It's working with Java 8
