### ISSUE TITLE
how to write part of sftp file with ChannelSftp  

### ISSUE THREAD

**Issue by YinChunGuang** [mwiede/jsch#527]
how to write part of sftp file with ChannelSftp  

Can I use the method ChannelSftp.put( String dist ,Int mode, Monitor m,long offset  )    by  setting the Offset with a nagtive value to Rewrite part of a sftp file.  Thank you ! @stsiano @chklauser @turbanoff

**Comment by norrisjeremy** [comment]
Hi @YinChunGuang,

Negative offsets are not legal for `SSH_FXP_WRITE` operations, since the offset is an unsigned integer value.

Thanks,
Jeremy
