### ISSUE TITLE
How do I enable ssh-rsa (RSA/SHA1) in the latest version? 

### ISSUE THREAD

**Issue by thirteen13Floor** [mwiede/jsch#553]
How do I enable ssh-rsa (RSA/SHA1) in the latest version?

**Comment by norrisjeremy** [comment]
Hi @thirteen13Floor,

This is answered in the [FAQ](https://github.com/mwiede/jsch?tab=readme-ov-file#why-do-ssh-rsa-type-keys-not-work-with-this-jsch-fork-and-my-server).

Thanks,
Jeremy
