### ISSUE TITLE
Invalid PrivateKey

### ISSUE THREAD

**Issue by raghulkrishna** [mwiede/jsch#561]
HI ,
I am testing the jsch Project for ssh somehow i can only use rsa keys not any format or sizes of open ssh keys

i have th test  project here https://github.com/raghulkrishna/jsch-test/blob/41a6e81f56e7168209ee539074c4f2f685882d7f/src/main/java/UserAuthPubKey.java

can you help me on this?

```
com.jcraft.jsch.JSchException: invalid privatekey: [B@49e202ad

```

**Comment by sbe-arg** [comment]
same here
