### ISSUE TITLE
 java.lang.ArrayIndexOutOfBoundsException with jsch version 0.2.18

### ISSUE THREAD

**Issue by swathimr** [mwiede/jsch#591]
I am using JSCH to connect to SFTP with high traffic and recently updated the library from com.jcraft. We saw this error recently and in local environment I am not able to reproduce the issue.

![Screenshot 2024-07-09 at 4 03 24 PM](https://github.com/mwiede/jsch/assets/8705617/bcb17881-bbe5-41b4-a13d-4555851ff534)

![Screenshot 2024-07-09 at 4 06 56 PM](https://github.com/mwiede/jsch/assets/8705617/50e498c5-1b7a-42c4-a94b-5e51c4b54975)
Can you please let me know whats causing this ?

**Comment by norrisjeremy** [comment]
You have a bug in your code.
The lines where you are calling `JSch.setConfig("server_host_key", ...)` and `JSch.setConfig("PubkeyAcceptedAlgorithms", ...)`, you are constantly appending `,ssh-rsa,ssh-dss` over and over to them every time you call your `getConnection()` method.

**Comment by swathimr** [comment]
I followed this listed here

**Comment by norrisjeremy** [comment]
JSch.setConfig() are static methods that act on global static state.
If you need to change this on a per-session basis, then you should use session.setConfig(), so that it doesn't constantly change global static state.

**Comment by swathimr** [comment]
okay I will try that. Does this issue occur only with the heavy load or multiple connects per session ?

**Comment by norrisjeremy** [comment]
Hi @swathimr,

This has nothing to do with heavy load or multiple connects: your code is simply flawed.

Thanks,
Jeremy
