### ISSUE TITLE
Is it possible to enable JSCH logs by just using java properties ?

### ISSUE THREAD

**Issue by EmmanuelM02** [mwiede/jsch#621]
Hi,

Sorry for my basic question but I am not a Java developer.

I am wondering if this is possible to enable JSCH logs by just using java properties that would be set at JVM level ?

something like -Dcom.jsch.logger.debug=true

Thanks in advance for your feedback.
Regards
Emmanuel

**Comment by norrisjeremy** [comment]
> Hi,
> 
> Sorry for my basic question but I am not a Java developer.
> 
> I am wondering if this is possible to enable JSCH logs by just using java properties that would be set at JVM level ?
> 
> something like -Dcom.jsch.logger.debug=true
> 
> Thanks in advance for your feedback. Regards Emmanuel

No.
