### ISSUE TITLE
unknown alg rsa-sha2-512

### ISSUE THREAD

**Issue by codelab360-cwcsh** [mwiede/jsch#690]
Hi, I'm working on SSH development with a specific piece of equipment.
I have implemented Connection with jsch 0.2.19 as the customer told me that their equipment uses rsa-sha2-512.

However, verify: false occurred, and when I enabled jsch's logs, the following problem occurred.

[INFO] 2024-10-24T18:04:30.062082200 - Connecting to xxx.xxx.xxx.xxx port xxx
[INFO] 2024-10-24T18:04:30.087503600 - Connection established
[INFO] 2024-10-24T18:04:30.099006200 - Remote version string: SSH-2.0-boXuN
[INFO] 2024-10-24T18:04:30.100012500 - Local version string: SSH-2.0-JSCH_0.2.19
[INFO] 2024-10-24T18:04:30.100012500 - CheckCiphers: chacha20-poly1305@openssh.com
[INFO] 2024-10-24T18:04:30.100012500 - CheckKexes: sntrup761x25519-sha512@openssh.com,curve25519-sha256,curve25519-sha256@libssh.org,curve448-sha512
[INFO] 2024-10-24T18:04:30.218873200 - sntrup761x25519-sha512@openssh.com is not available.
[DEBUG] 2024-10-24T18:04:30.218873200 - kex proposal before removing unavailable algos is: diffie-hellman-group-exchange-sha256,ssh-rsa,rsa-sha2-512,diffie-hellman-group1-sha1,ssh-dss,rsa-sha2-256,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha1,diffie-hellman-group16-sha512,ecdh-sha2-nistp256,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,ecdh-sha2-nistp521,ecdsa-sha2-nistp256,curve25519-sha256@libssh.org,ecdsa-sha2-nistp521,curve25519-sha256,ecdh-sha2-nistp384,ecdsa-sha2-nistp384
[DEBUG] 2024-10-24T18:04:30.220128600 - kex proposal after removing unavailable algos is: diffie-hellman-group-exchange-sha256,ssh-rsa,rsa-sha2-512,diffie-hellman-group1-sha1,ssh-dss,rsa-sha2-256,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha1,diffie-hellman-group16-sha512,ecdh-sha2-nistp256,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,ecdh-sha2-nistp521,ecdsa-sha2-nistp256,curve25519-sha256@libssh.org,ecdsa-sha2-nistp521,curve25519-sha256,ecdh-sha2-nistp384,ecdsa-sha2-nistp384
[INFO] 2024-10-24T18:04:30.220128600 - CheckSignatures: ssh-ed25519,ssh-ed448
[DEBUG] 2024-10-24T18:04:30.225790900 - server_host_key proposal before known_host reordering is: rsa-sha2-512,ssh-rsa,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,ssh-dss,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519,ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,diffie-hellman-group-exchange-sha1
[DEBUG] 2024-10-24T18:04:30.233081800 - server_host_key proposal after known_host reordering is: rsa-sha2-512,ssh-rsa,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,ssh-dss,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519,ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,diffie-hellman-group-exchange-sha1
[INFO] 2024-10-24T18:04:30.234132 - SSH_MSG_KEXINIT sent
[INFO] 2024-10-24T18:04:30.234132 - SSH_MSG_KEXINIT received
[INFO] 2024-10-24T18:04:30.235136600 - server proposal: KEX algorithms: diffie-hellman-group-exchange-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521
[INFO] 2024-10-24T18:04:30.235136600 - server proposal: host key algorithms: rsa-sha2-512,ssh-ed25519
[INFO] 2024-10-24T18:04:30.235136600 - server proposal: ciphers c2s: aes256-ctr,aes256-gcm@openssh.com
[INFO] 2024-10-24T18:04:30.235136600 - server proposal: ciphers s2c: aes256-ctr,aes256-gcm@openssh.com
[INFO] 2024-10-24T18:04:30.236136800 - server proposal: MACs c2s: hmac-sha2-256,hmac-sha2-256-etm@openssh.com,hmac-sha2-512,hmac-sha2-512-etm@openssh.com
[INFO] 2024-10-24T18:04:30.236136800 - server proposal: MACs s2c: hmac-sha2-256,hmac-sha2-256-etm@openssh.com,hmac-sha2-512,hmac-sha2-512-etm@openssh.com
[INFO] 2024-10-24T18:04:30.236136800 - server proposal: compression c2s: none,zlib@openssh.com
[INFO] 2024-10-24T18:04:30.236136800 - server proposal: compression s2c: none,zlib@openssh.com
[INFO] 2024-10-24T18:04:30.236136800 - server proposal: languages c2s: 
[INFO] 2024-10-24T18:04:30.236136800 - server proposal: languages s2c: 
[INFO] 2024-10-24T18:04:30.237137500 - client proposal: KEX algorithms: diffie-hellman-group-exchange-sha256,ssh-rsa,rsa-sha2-512,diffie-hellman-group1-sha1,ssh-dss,rsa-sha2-256,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha1,diffie-hellman-group16-sha512,ecdh-sha2-nistp256,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,ecdh-sha2-nistp521,ecdsa-sha2-nistp256,curve25519-sha256@libssh.org,ecdsa-sha2-nistp521,curve25519-sha256,ecdh-sha2-nistp384,ecdsa-sha2-nistp384,ext-info-c,kex-strict-c-v00@openssh.com
[INFO] 2024-10-24T18:04:30.237137500 - client proposal: host key algorithms: rsa-sha2-512,ssh-rsa,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,ssh-dss,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519,ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,diffie-hellman-group-exchange-sha1
[INFO] 2024-10-24T18:04:30.237137500 - client proposal: ciphers c2s: aes256-gcm@openssh.com,aes192-ctr,aes256-cbc,aes256-ctr,arcfour,arcfour128,aes192-cbc,aes128-ctr,aes128-cbc,blowfish-cbc,aes128-gcm@openssh.com,3des-cbc,3des-ctr
[INFO] 2024-10-24T18:04:30.237137500 - client proposal: ciphers s2c: aes256-gcm@openssh.com,aes192-ctr,aes256-cbc,aes256-ctr,arcfour,arcfour128,aes192-cbc,aes128-ctr,aes128-cbc,blowfish-cbc,aes128-gcm@openssh.com,3des-cbc,3des-ctr
[INFO] 2024-10-24T18:04:30.237137500 - client proposal: MACs c2s: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[INFO] 2024-10-24T18:04:30.237137500 - client proposal: MACs s2c: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
[INFO] 2024-10-24T18:04:30.237137500 - client proposal: compression c2s: none
[INFO] 2024-10-24T18:04:30.237137500 - client proposal: compression s2c: none
[INFO] 2024-10-24T18:04:30.238136200 - client proposal: languages c2s: 
[INFO] 2024-10-24T18:04:30.239137200 - client proposal: languages s2c: 
[INFO] 2024-10-24T18:04:30.241602300 - kex: algorithm: diffie-hellman-group-exchange-sha256
[INFO] 2024-10-24T18:04:30.241602300 - kex: host key algorithm: rsa-sha2-512
[INFO] 2024-10-24T18:04:30.241602300 - kex: server->client cipher: aes256-gcm@openssh.com MAC: <implicit> compression: none
[INFO] 2024-10-24T18:04:30.241602300 - kex: client->server cipher: aes256-gcm@openssh.com MAC: <implicit> compression: none
[INFO] 2024-10-24T18:04:30.282094200 - SSH_MSG_KEX_DH_GEX_REQUEST(2048<3072<8192) sent
[INFO] 2024-10-24T18:04:30.282094200 - expecting SSH_MSG_KEX_DH_GEX_GROUP
[INFO] 2024-10-24T18:04:30.478256800 - SSH_MSG_KEX_DH_GEX_INIT sent
[INFO] 2024-10-24T18:04:30.478256800 - expecting SSH_MSG_KEX_DH_GEX_REPLY

> **[ERROR] 2024-10-24T18:04:30.651023 - unknown alg: rsa-sha2-512**

[INFO] 2024-10-24T18:04:30.651023 - Disconnecting from xxx.xxx.xxx.xxx port xxx

I don't know anything as deep as the authentication key algorithm, but through debugging I realized that there was no handling for when "rsa-sha2-512" comes up in the variable alg, so I added it to KeyExchange.java.
Also, HostKey.java, which checks the hostkey, had no handling for the value sent by this device in the part that checks for bytes, so i fixed that.

I think you can find the fix at this address.
https://github.com/codelab360-cwcsh/jsch

I did this because I don't know the standard conventions, what do you think of my modifications?
I'd love to hear your feedback. 
thank you.

**Comment by norrisjeremy** [comment]
Hi @codelab360-cwcsh,

This equipment appears to have a broken SSH server implementation that is not [RFC-8332](https://datatracker.ietf.org/doc/html/rfc8332) compliant.
I would recommend that you open an issue with the authors of the SSH server implementation and ask them to fix their implementation.

Thanks,
Jeremy
