### ISSUE TITLE
BouncyCastle NoSuchMethodError

### ISSUE THREAD

**Issue by Fabio1988** [mwiede/jsch#77]
Hey, I switched from latest com.jcraft:jsch to your repo.
I read of the missing config for older servers but I receive a different error.

```
java.lang.NoSuchMethodError: org.bouncycastle.crypto.params.X25519PublicKeyParameters.<init>([B)V

	at com.jcraft.jsch.bc.XDH.getSecret(XDH.java:71)
	at com.jcraft.jsch.DHXEC.next(DHXEC.java:144)
	at com.jcraft.jsch.Session.connect(Session.java:330)
```

I use JSch inside Spring Application to provide SSH command executions. I tried #37 and #40, but those settings doesn't help. Any hint?

**Comment by Fabio1988** [comment]
`session.setConfig("kex", "diffie-hellman-group1-sha1");`

Maybe only this config worked... There is also a second config-line, which doesn't work...

So with this fix it will support old ssh connections.. But also the new ones?

**Comment by norrisjeremy** [comment]
Hi @Fabio1988,

What version of Bouncy Castle (bcprov-jdk15on) are you utilizing?

Thanks,
Jeremy

**Comment by norrisjeremy** [comment]
Hi @Fabio1988,

Are you sure? The exception you posted seems to indicate that the class `org.bouncycastle.crypto.params.X25519PublicKeyParameters` lacks the constructor type `public X25519PublicKeyParameters(byte[] buf)`. This particular constructor appears to have only been added in version 1.69. Perhaps you have somehow pulled in an older release onto your classpath? I can attempt to address this in the next JSch release, to add some amount of backwards compatibility for older Bouncy Castle releases.

Thanks,
Jeremy

**Comment by Fabio1988** [comment]
Hi @norrisjeremy 
thanks for your answer. I'm pretty sure I use 1.69 since July :) 

The exception is away after adding `session.setConfig("kex", "diffie-hellman-group1-sha1");` Hopefully it will work, have to test it properly.
But I think some backwards compatibility would be nice too :)

**Comment by norrisjeremy** [comment]
Hi @Fabio1988,

What version of Java are you utilizing?

Thanks,
Jeremy

**Comment by Fabio1988** [comment]
Java 8.. Will update this year to latest LTS 17 :+1:

**Comment by Fabio1988** [comment]
Is it possible to use those minor updates PR with gradle build? not really I think?! :)

**Comment by mwiede** [comment]
I will quickly release changes  of #70 since there are enough intergration tests which covers the functionality.

**Comment by norrisjeremy** [comment]
Hi @Fabio1988,

Can you confirm if the new 0.1.67 release fixes the `java.lang.NoSuchMethodError` you were receiving?

Thanks,
Jeremy

**Comment by Fabio1988** [comment]
Hi @norrisjeremy 

Thanks a lot, that fixed the Exception :)
