### ISSUE TITLE
ssh-ed25519 not available for identity my_key

### ISSUE THREAD

**Issue by repon06** [mwiede/jsch#81]
I use<version>0.1.67</version>.
```
        ...
	JSch jsch = new JSch();
        jsch.setKnownHosts("src/test/resources/known_hosts");
        jsch.addIdentity("src/test/resources/id_ed25519", "");
        Session session = jsch.getSession(jumpServerUsername, jumpServerHost, 22);
        Properties config = new Properties();
        config.put("StrictHostKeyChecking", "no");
        config.put("Compression", "yes");
        config.put("ConnectionAttempts","2");
        session.setConfig(config);

        session.connect(2500); //<- com.jcraft.jsch.JSchException: Auth fail
	...
	int forwardedPort = session.setPortForwardingL(0, databaseHost, databasePort);
```

Logging:
```
PubkeyAcceptedAlgorithms = ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa
Signature algorithms unavailable for non-agent identities = [ssh-ed25519, ssh-ed448]
PubkeyAcceptedAlgorithms in server-sig-algs = [ssh-ed25519, ecdsa-sha2-nistp256, ecdsa-sha2-nistp384, ecdsa-sha2-nistp521, rsa-sha2-512, rsa-sha2-256, ssh-rsa]
ssh-ed25519 not available for identity D:\git\repon\***\src\test\resources\id_ed25519
Disconnecting from *.*.** port 22
```

What am I doing wrong?

**Comment by norrisjeremy** [comment]
Hi @repon06,

Are you using Java 15 or newer? If not, then you will need to add Bouncy Castle (`bcprov-jdk15on`) to your classpath in order to use `ssh-ed25519` type keys.

Thanks,
Jeremy

**Comment by repon06** [comment]
> Hi @repon06,
> 
> Are you using Java 15 or newer? If not, then you will need to add Bouncy Castle (`bcprov-jdk15on`) to your classpath in order to use `ssh-ed25519` type keys.
> 
> Thanks,
> Jeremy

i use **jdk-11.0.7**
we need to add it to the project?
```
<dependency>
    <groupId>org.bouncycastle</groupId>
    <artifactId>bcprov-jdk15on</artifactId>
    <version>1.69</version>
</dependency>
```

**Comment by norrisjeremy** [comment]
> i use **jdk-11.0.7**
> we need to add it to the project?
> 
> ```
> <dependency>
>     <groupId>org.bouncycastle</groupId>
>     <artifactId>bcprov-jdk15on</artifactId>
>     <version>1.69</version>
> </dependency>
> ```

Hi @repon06,

Yes, in order to use `ssh-ed25519` type keys with Java 11 you would need to add a Bouncy Castle dependency (`bcprov-jdk15on`) to your application.

Additionally, if your application is using the Java module system introduced in Java 9+, you will like need to add `requires org.bouncycastle.provider;` into your `module-info.java` descriptor in order to make the Bouncy Castle library available to JSch.

Thanks,
Jeremy

**Comment by repon06** [comment]
Thank you very much! it works!

**Comment by norrisjeremy** [comment]
Hi @repon06,

I'm glad to hear that!

Thanks,
Jeremy
