### ISSUE TITLE
comply with RFC4253 / 4.2 Protocol Version Exchange - missing CR in identification string

### ISSUE THREAD

**Issue by LuckyDams** [mwiede/jsch#83]
Hi, 

Recent CISCO devices are complaining against missing CR in identification string:  
`DAEMON-3-SYSTEM_MSG: error: protocol identification string lack carriage return - dcos_sshd[14616]`

Based on [RFC4253 section 4.2](https://datatracker.ietf.org/doc/html/rfc4253#section-4.2), identification string must be:  
`SSH-protoversion-softwareversion SP comments CR LF`

Spent very few times on sources but it seems a fix would only need following changes in [src/main/java/com/jcraft/jsch/Session.java](https://github.com/mwiede/jsch/blob/master/src/main/java/com/jcraft/jsch/Session.java):  
![session_fix](https://user-images.githubusercontent.com/43099755/136036358-97d2bf18-9347-4cc5-ad1f-aa95d9af8b1a.png)

Would you kindly review & consider implementing a fix ?
Thank you.

**Comment by norrisjeremy** [comment]
Hi @LuckyDams,

I believe this issue should be resolved in the [0.1.69](https://github.com/mwiede/jsch/releases/tag/jsch-0.1.69) release.

Thanks,
Jeremy

**Comment by norrisjeremy** [comment]
Hi @LuckyDams,

Can this be closed now?

Thanks,
Jeremy

**Comment by LuckyDams** [comment]
Hi,

Yes sure. Sorry for this late reply.

Rgds,
Luc

Le jeu. 3 févr. 2022, 20:31, Jeremy Norris ***@***.***> a
écrit :
